
var metaByFieldValue={

    

  "firstName":{"label":"First Name", 
    "1":"One: Leader, Achiever, Independent. Gift: Confidence. Challenge: Victim.",
    "2":"Two: Partner, intuitive, patient. Gift: Compatible. Challenge: Fearful.",
    "3":"Three: Creative, visionary, social. Gift: Intelligent. Challenge: Scattered.",
    "4":"Four: Builder, practical, service. Gift: Reliable. Challenge: Stubborn.",
    "5":"Five: Adventurer, freedom, passion. Gift: Versatile. Challenge: Chaos.",
    "6":"Six: Teacher, counselor, healer. Gift: Generous. Challenge: Martyr.",
    "7":"Seven: Investigator, eccentric, spiritual. Gift: Analytical. Challenge: Trust.",
    "8":"Eight: Problem solver, material satisfaction. Gift: Organizational. Challenge: Rigid.",
    "9":"Nine: Humanitarian, multi-talented. Gift: Philanthropic. Challenge: Aloof.",
    "11/2":"11/2 Master Number: Inspirer. Gift: Empathic. Challenge: Over sensitive.",
    "22/4":"22/4 Master Number: Master Builder. Gift: Large undertakings. Challenge: Resistant.",
    "33/6":"33/6 Master Number: Master Teacher. Gift: Selfless service. Challenge: Mushy boundaries.",
    "13/4":"13/4 Karmic Number. Four: Builder, practical, service. Gift: Reliable. Challenge: Stubborn.",
    "14/5":"14/5 Karmic Number. Five: Adventurer, freedom, passion. Gift: Versatile. Challenge: Chaos.",
    "16/7":"16/7 Karmic Number. Seven: Investigator, eccentric, spiritual. Gift: Analytical. Challenge: Trust.",
    "19/1":"19/1 Karmic Number. One: Leader, Achiever, Independent. Gift: Confidence. Challenge: Victim."
    },
    
 "middleName":{"label":"Middle Name", 
    "1":"One: Leader, Achiever, Independent. Gift: Wordsmith, Confidence. Challenge: Victim.",
    "2":"Two: Partner, intuitive, patient. Gift: Compatible. Challenge: Fearful.",
    "3":"Three: Creative, visionary, social. Gift: Intelligent. Challenge: Scattered.",
    "4":"Four: Builder, practical, service. Gift: Reliable. Challenge: Stubborn.",
    "5":"Five: Adventurer, freedom, passion. Gift: Versatile. Challenge: Chaos.",
    "6":"Six: Teacher, counselor, healer. Gift: Generous. Challenge: Martyr.",
    "7":"Seven: Investigator, eccentric, spiritual. Gift: Analytical. Challenge: Trust.",
    "8":"Eight: Problem solver, material satisfaction. Gift: Organizational. Challenge: Rigid.",
    "9":"Nine: Humanitarian, multi-talented. Gift: Philanthropic. Challenge: Aloof.",
    "11/2":"11/2 Master Number: Inspirer. Gift: Empathic. Challenge: Over sensitive.",
    "22/4":"22/4 Master Number: Master Builder. Gift: Large undertakings. Challenge: Resistant.",
    "33/6":"33/6 Master Number: Master Teacher. Gift: Selfless service. Challenge: Mushy boundaries.",
    "13/4":"13/4 Karmic Number. Four: Builder, practical, service. Gift: Reliable. Challenge: Stubborn.",
    "14/5":"14/5 Karmic Number. Five: Adventurer, freedom, passion. Gift: Versatile. Challenge: Chaos.",
    "16/7":"16/7 Karmic Number. Seven: Investigator, eccentric, spiritual. Gift: Analytical. Challenge: Trust.",
    "19/1":"19/1 Karmic Number. One: Leader, Achiever, Independent. Gift: Confidence. Challenge: Victim."
    },
    
"lastName":{"label":"Last Name", 
    "1":"One: Leader, Achiever, Independent. Gift: Confidence. Challenge: Victim.",
    "2":"Two: Partner, intuitive, patient. Gift: Compatible. Challenge: Fearful.",
    "3":"Three: Creative, visionary, social. Gift: Intelligent. Challenge: Scattered.",
    "4":"Four: Builder, practical, service. Gift: Reliable. Challenge: Stubborn.",
    "5":"Five: Adventurer, freedom, passion. Gift: Versatile. Challenge: Chaos.",
    "6":"Six: Teacher, counselor, healer. Gift: Generous. Challenge: Martyr.",
    "7":"Seven: Investigator, eccentric, spiritual. Gift: Analytical. Challenge: Trust.",
    "8":"Eight: Problem solver, material satisfaction. Gift: Organizational. Challenge: Rigid.",
    "9":"Nine: Humanitarian, multi-talented. Gift: Philanthropic. Challenge: Aloof.",
    "11/2":"11/2 Master Number: Inspirer. Gift: Empathic. Challenge: Over sensitive.",
    "22/4":"22/4 Master Number: Master Builder. Gift: Large undertakings. Challenge: Resistant.",
    "33/6":"33/6 Master Number: Master Teacher. Gift: Selfless service. Challenge: Mushy boundaries.",
    "13/4":"13/4 Karmic Number. Four: Builder, practical, service. Gift: Reliable. Challenge: Stubborn.",
    "14/5":"14/5 Karmic Number. Five: Adventurer, freedom, passion. Gift: Versatile. Challenge: Addictive tendencies.",
    "16/7":"16/7 Karmic Number. Seven: Investigator, eccentric, spiritual. Gift: Analytical. Challenge: Suspicious.",
    "19/1":"19/1 Karmic Number. One: Leader, Achiever, Independent. Gift: Confidence. Challenge: Victim."
    },
  "dayOfBirth":{"label":"Day of Birth",
    "1":"One: Leader, Pioneer, Achiever. Stands out from the crowd, idealistic, pragmatic, loves to plan, strong will, needs a goal to work towards, values loyalty, needs things to be done correctly, loves deeply",
    "2":"Two: Sensitive, Emotional, Supportive. Peacemaker, patient, excel at detail work, social life and mate are most important to your life, crave affection, remember others' birthdays, look for ulterior motives, talent for music and arts, love beautiful things",
    "3":"Three: Happy Outgoing, Optimistic. Charming, quick to see humor, somewhat unreliable, keeps busy, distractible, has many friends, gives gifts, story teller, generous, youthfulness, intensity in style, loved by others, needs creative hobbies",
    "4":"Four: Builder, Manager, Traditionalist. Succeeds through business, management production and anything connected to building and the earth.  Tends to be cautious, careful, and fundamental.  Must work to stay up-t0-date. Strong ideas about the right way to do things.",
    "5":"Five: Active, Adaptable, Curious. Traveler, promoter, storyteller, jokester.  Marry late to explore first. Tends to be alert, curious, questioning, and needs work that s challenging, risky, and different.",
    "6":"Six: Parent, Teacher, Healer. Loving but territorial. Loves luxury and craves romantic attention. Scarcity is on your mind.  Friends and family come first. Values social position, contacts, and reciprocity.",
    "7":"Seven: Intellectual, Intuitive, Technical. Success comes from concentrating on one thing at a time. Follow your hunches.  Tends to be cautious with money, have strong opinions, quiet, and focuses on a few friends.  Does well farming, ranching, playing instruments, and does well in fields requiring specialized training.",
    "8":"Eight: Leader, Manager, Professional. Ambitious, motivated, serious, mature, disciplined, competent, independent, dominant.  Needs a career or business providing a challenge. Rises into leadership roles. Can be cynical or bitter if not successful. ",
    "9":"Nine:Broad-Minded, Idealistic, Loving. Idealistic, emotional, indecisive, cable, metaphysical outlook to world problems. Does well in fields of art, healing, teaching, philanthropy, or music.",
    "10":"One: Leader, Pioneer, Achiever. Has a great deal of vitality. Recovers easily from any setback. Creative, forward thinking, indispensable.  Has many interests.  Does well in design.",
    "11/2":"Two: Sensitive, Emotional, Supportive. 11/2 Master number of inspiration. Especially sensitive. Does well in the limelight in television, poetry, metaphysics, art, psychology, or spiritual work. Seem to always to be on the verge of success while yearning to do something almost impossible.  Needs to stay grounded.",
    "12":"Three: Happy Outgoing, Optimistic. Idealistic, logical, brilliant, easily bored, magnetic, expressive, persuasive, convincing. Needs to charm and flirt. Loves media and celebrities. Does well in photography with a good eye for color and design.",
    "13/4":"Four: Builder, Manager, Traditionalist. Does well in manufacturing, commerce, real estate, remodeling, building. Can reform or improve any situation or condition. Ignores feelings until they blow up. Has good verbal expression and creative abilities.",
    "14/5":"Five: Active, Adaptable, Curious. Vigorous, competitive, can be disciplined for short-term goals, opinionated, eccentric. Lives a most interesting life while overcoming obstacles. Meets people for karmic connections. Crave stimulation and experimentation. Does well being in own business such as travel, promotion, the public, performing or entertaining.",
    "15":"Six: Parent, Teacher, Healer. Open-minded, spirited, independent, well-travelled, creative.  Does well as a fashion designer, interior designer, emergency nurse or teacher. Treats family as first priority and values own home. Sought out for advice. Tends to have a pleasing voice. Needs a wide circle of educated friends.",
    "16/7":"Seven: Intellectual, Intuitive, Technical. 16/7 Karmic number. Life brings startling events as turning points. Tends to have unusual friends with karmic connections. Tends to learn things the hard way and procrastinate. Does well pursuing technical or historical fields.  May invent or discover something entirely new.",
    "17":"Eight: Leader, Manager, Professional. Dynamic go-getter, daring, courage to undertake large projects, executive ability to delegate, has vision and determination.  Excellent judgement and integrity. Tends to be a good problem solver. Admires scholars and historians.  Excels at technical factual writing.",
    "18":"Nine:Broad-Minded, Idealistic, Loving. Has the drive and ambition of the One and the executive capacity of the Eight. Has good critical powers.  Does well in drama, art or music.  Needs to work for the good of others.  Needs to push to get past obstacles by acquiring more knowledge and understanding.",
    "19/1":"One: Leader, Pioneer, Achiever. 19/1 is a Karmic Number.  Has a special direction of goal in life. Life is complex due to desire to excel and the need to be of service and influence many people. Extremely discerning, perceptive, aloof, formal, keen sense of humor, dry wit, self-controlled.  Can be cynical or rigid.",
    "20":"Two: Sensitive, Emotional, Supportive. Conscientious, friendly, compassionate, eager to help.  Does well as a sensitive therapist, artist, photographer, writer while in a  small business. Attracted to spiritual matters. Strong attention to detail and appreciation of order.",
    "21":"Three: Happy Outgoing, Optimistic. Very sensitive, thinks before speaking, great imagination, prone to dreaming, natural singer or songwriter.  Tends to be high-strung and should avoid analyzing too much. Avoids manual labor.  Might be gullible. Tends to have infatuations.",
    "22/4":"Four: Builder, Manager, Traditionalist. 22/4 Master number.  Works for universal good rather than personal ambition. Displays originality, competence, single-mindedness.  Tends to be sensitive, analytical and judgmental. Benefits from spiritual study.  Competent at any undertaking.  Experiences help large projects.",
    "23":"Five: Active, Adaptable, Curious. Independent, self-sufficient, verbal, expressive, witty, sometimes defiant, persuasive, youthful. Interested in art, music, or new age ideals. Turns events to personal advantage. Can be petty and critical under stress.  Knows what other people with buy.",
    "24":"Six: Parent, Teacher, Healer. Careful, cautious, productive. Feels like a liberal but others may not agree.  Wants to build a family empire to accumulate wealth for self and others. Does well in teaching, accounting, banking or real estate. Admires creative and spontaneous people.",
    "25":"Seven: Intellectual, Intuitive, Technical. Intuitive, impressionable and highly emotional. Tends to excel at art, music, and working with animals. Important to find a stable diet and exercise routine. Tends to be hard to understand by others.",
    "26":"Eight: Leader, Manager, Professional. Has strong emotional capacity. Loves nature and harmony. Dresses well.  Has a fine house and well-brought-up children. Generous, introspective, and psychologically analytical.  Does well in a catering business, diplomacy or administrative work in the social sciences.",
    "27":"Nine:Broad-Minded, Idealistic, Loving. Is a keen observer of life. Yearns for distant places. Does well as a journalist, wildlife photographer, calligrapher, or antique dealer.  Needs an ideal to follow and to learn how to let go.  Tends to be generous and forgiving of friends.",
    "28":"One: Leader, Pioneer, Achiever. Loves independence, freedom, being the center of attention, and having quality friends.  Does well as a teacher, lawyer, engineer, architect or designer. Tends to be an executive.  Has a dramatic flair.",
    "29":"Two: Sensitive, Emotional, Supportive. Also a 11/2 master number. Has heightened spiritual interests.  Must manage moods before getting out of hand. Inspires others and attracts the limelight. Does well as a teacher, artist, gardener, cook, tailor, or builder. Often has two occupations with one supporting artistic pursuits. ",
    "30":"Three: Happy Outgoing, Optimistic. Has high energy and infectious enthusiasm. Outspoken, psychic, serious, intense, flirtatious. Motivates and persuades others. Knack for just the right word or fact to win an argument. Does well as a teacher, speaker, lawyer, actor or musician.",
    "31":"Four: Builder, Manager, Traditionalist. Does well working hands-on as a sculptor or painter. Ambitious, traditional, and loves to travel and socialize. Works long hours when motivated.  Expects people to be interested in stories about self and plans.  Likes to live with someone and pays close attention to them."
    },

  "birthpath":{"label":"Birthpath: I am!",
    "1":"One: Decisive, courageous, leader, honest, active, dynamic, witty, impatient, innovative, independent, assertive, original, quick, inventive, mental, strong, principled",
    "2":"Two: Cooperative, tactful, patient, self-effacing, collector, understanding, timid, indecisive, sensitive, supportive, unassuming, diplomatic, quiet, listener",
    "3":"Three: expressive, social, charming, visionary, friendly, joyful, creative, easy going, joking, pleasure loving, artistic, optimistic, imaginative, gregarious, fun loving, persuasive, dramatic, generous",
    "4":"Four: traditional, conservative, reliable, focused, disciplined, quiet, cautious, quiet, systematic, practical, sensible, rational, honest, realistic, loyal, hardworking, serious",
    "5":"Five: nonconforming, active, versatile, flirtatious, speedy, clever, gregarious, enthusiastic, magnetic, impulsive, competitive, affectionate, adventurous, quick, different, charismatic, persuasive, sensual",
    "6":"Six: domestic, nurturing, teacher, counselor, conventional, moral, consistent, generous, loyal, determined, compromising, judgmental, responsible, care giver, friendly, dependable, loving, practical, traditional",
    "7":"Seven: serious, specialist, perfectionist, elegant, superior, knowledgeable, thinker, connected, self-sufficient, unconventional, secretive, skeptic, wizard, magician, quiet, refined, intellectual, studious, cautious, analytical, deep, selective",
    "8":"Eight: Strong, forceful, money minded, decisive, authoritative, professional, direct, masterful, problem solver, spiritual, powerful, ambitious, conservative, confident, efficient, formal, discerning, reliable",
    "9":"Nine: philosophical, wise, dramatic, religious, lover, tolerant, resourceful, intuitive, powerful, friendly, detached, fortunate, humanitarian, dreamer, poetic, generous, universal, dynamic, evolved, impressionable, global, neutral",
    "11/2":"11/2: inspirational, poetic, romantic, refined, aesthetic, famous, feminine, passive, intense, eccentric, fussy, sensitive, achiever, celebrity, enthusiastic, idealistic, spiritual, imaginative, intuitive",
    "22/4":"22/4: masterful, builder, mission driven, intuitive, competent, visionary, efficient, expert, honest, hardworking, rational, leader, practical, spiritual, accomplished, powerful, assured, confident",
    "33/6":"33/6: compassionate, teacher, wise, loving, caring, healer, care giver, understanding, impulsive, visionary, creative, generous, creative, imaginative, playful, optimistic, friendly, storyteller, community builder",
    "13/4":"13/4 Karmic Number. Four: traditional, conservative, reliable, focused, disciplined, quiet, cautious, quiet, systematic, practical, sensible, rational, honest, realistic, loyal, hardworking, serious",
    "14/5":"14/5 Karmic Number. Five: nonconforming, active, versatile, flirtatious, speedy, clever, gregarious, enthusiastic, magnetic, impulsive, competitive, affectionate, adventurous, quick, different, charismatic, persuasive, sensual, impulsive",
    "16/7":"16/7 Karmic Number. Seven: serious, specialist, perfectionist, elegant, superior, knowledgeable, thinker, observant, solitary, eccentric, secretive, skeptic, wizard, magician, quiet, refined, intellectual, studious, cautious, analytical, deep, selective",
    "19/1":"19/1 Karmic Number. One: Decisive, courageous, leader, honest, active, dynamic, witty, patient, innovative, independent, assertive, original, quick, inventive, mental, strong, principled"
    },



  "destiny":{"label":"Destiny:  You must become!",
    "0":"",
    "1":"One: Decisive, courageous, leader, honest, active, dynamic, witty, patient, innovative, independent, assertive, original, quick, inventive, mental, strong, principled",
    "2":"Two: Cooperative, tactful, patient, humble, collaborative, understanding, assured, decisive, sensitive, supportive, unassuming, diplomatic, quiet, listener",
    "3":"Three: expressive, social, charming, visionary, friendly, joyful, creative, easygoing, joking, pleasure loving, artistic, optimistic, imaginative, gregarious, fun loving, persuasive, dramatic, generous",
    "4":"Four: traditional, conservative, reliable, focused, disciplined, quiet, cautious, quiet, systematic, decisive, practical, sensible, rational, honest, realistic, loyal, hardworking, serious",
    "5":"Five: nonconforming, active, versatile, flirtatious, speedy, clever, gregarious, enthusiastic, magnetic, impulsive, competitive, affectionate, adventurous, quick, different, charismatic, persuasive, sensual, impulsive",
    "6":"Six: domestic, nurturing, teacher, counselor, conventional, moral, consistent, generous, loyal, determined, compromising, judgmental, responsible, care giver, friendly, dependable, loving, practical, traditional",
    "7":"Seven: serious, specialist, perfectionist, elegant, superior, knowledgeable, thinker, connected, self-sufficient, eccentric, secretive, skeptic, wizard, magician, quiet, refined, intellectual, studious, cautious, analytical, deep, selective",
    "8":"Eight: Strong, forceful, money minded, decisive, authoritative, professional, direct, masterful, problem solver, spiritual, demanding, powerful, ambitious, conservative, confident, efficient, formal, discerning, reliable",
    "9":"Nine: philosophical, wise, dramatic, religious, lover, tolerant, resourceful, intuitive, powerful, connected, detached, fortunate, humanitarian, dreamer, poetic, generous, universal, dynamic, evolved, impressionable, global, neutral",
    "11/2":"11/2: inspirational, poetic, romantic, refined, visual, famous, feminine, passive, intense, eccentric, fussy, assured, sensitive, achiever, celebrity, enthusiastic, idealistic, spiritual, imaginative, intuitive",
    "22/4":"22/4: masterful, builder, mission driven, intuitive, competent, visionary, efficient, expert, honest, hardworking, rational, leader, practical, spiritual, accomplished, powerful, assured, confident, assured",
    "33/6":"33/6: compassionate, teacher, wise, loving, caring, healer, care giver, understanding, impulsive, visionary, creative, generous, creative, imaginative, playful, optimistic, friendly, storyteller, community builder",
    "13/4":"13/4 Karmic Number. Four: traditional, conservative, reliable, focused, disciplined, quiet, cautious, quiet, systematic, decisive, practical, sensible, rational, honest, realistic, loyal, hardworking, serious",
    "14/5":"14/5 Karmic Number. Five: nonconforming, active, versatile, flirtatious, speedy, clever, gregarious, enthusiastic, magnetic, impulsive, competitive, affectionate, adventurous, quick, different, charismatic, persuasive, sensual, impulsive",
    "16/7":"16/7 Karmic Number. Seven: serious, specialist, perfectionist, elegant, superior, knowledgeable, thinker, aloof, solitary, eccentric, secretive, skeptic, wizard, magician, quiet, refined, intellectual, studious, cautious, analytical, deep, selective",
    "19/1":"19/1 Karmic Number. One: Decisive, courageous, leader, honest, active, dynamic, witty, impatient, innovative, independent, assertive, original, quick, inventive, mental, strong, principled"
    },
  "realization":{"label":"Realization: What you will be",
    "0":"",
    "1":"One: decisive, courageous, leader, honest, active, dynamic, witty, tolerant, innovative, independent, assertive, original, quick, inventive, mental, strong, principled",
    "2":"Two: cooperative, tactful, patient, humble, collaborative, understanding, assured, decisive, sensitive, supportive, unassuming, diplomatic, quiet, listener",
    "3":"Three: expressive, social, charming, visionary, friendly, joyful, creative, easygoing, joking, pleasure loving, artistic, optimistic, imaginative, gregarious, fun loving, persuasive, dramatic, generous",
    "4":"Four: traditional, conservative, reliable, focused, disciplined, quiet, cautious, quiet, systematic, decisive, practical, sensible, rational, honest, realistic, loyal, hardworking, serious",
    "5":"Five: nonconforming, active, versatile, flirtatious, speedy, clever, gregarious, enthusiastic, magnetic, impulsive, competitive, affectionate, adventurous, quick, different, charismatic, persuasive, sensual, impulsive, free to choose",
    "6":"Six: domestic, nurturing, teacher, counselor, conventional, moral, consistent, generous, loyal, determined, compromising, understanding, responsible, care giver, friendly, dependable, loving, practical, traditional",
    "7":"Seven: serious, specialist, perfectionist, elegant, superior, knowledgeable, thinker, observant, solitary, eccentric, secretive, skeptic, wizard, magician, quiet, refined, intellectual, studious, cautious, analytical, deep, selective",
    "8":"Eight: strong, forceful, money minded, decisive, authoritative, professional, direct, masterful, problem solver, spiritual, powerful, ambitious, conservative, confident, efficient, formal, discerning, reliable",
    "9":"Nine: philosophical, wise, dramatic, religious, lover, tolerant, resourceful, intuitive, powerful, friendly, detached, fortunate, humanitarian, dreamer, poetic, generous, universal, dynamic, evolved, impressionable, global, distant",
    "11/2":"11/2: inspirational, poetic, romantic, refined, aesthetic, famous, feminine, passive, intense, eccentric, fussy, assured, sensitive, achiever, celebrity, enthusiastic, idealistic, spiritual, imaginative, intuitive",
    "22/4":"22/4: masterful, builder, mission driven, intuitive, competent, visionary, efficient, expert, honest, hardworking, rational, leader, practical, spiritual, accomplished, powerful, assured, confident, assured",
    "33/6":"33/6: compassionate, teacher, wise, loving, caring, healer, care giver, understanding, impulsive, visionary, creative, generous, creative, imaginative, playful, optimistic, friendly, storyteller, community builder",
     "13/4":"13/4 Karmic Number. Four: traditional, conservative, reliable, focused, disciplined, quiet, cautious, quiet, systematic, decisive, practical, sensible, rational, honest, realistic, loyal, hardworking, serious",
    "14/5":"14/5 Karmic Number. Five: nonconforming, active, versatile, flirtatious, speedy, clever, gregarious, enthusiastic, magnetic, impulsive, competitive, affectionate, adventurous, quick, different, charismatic, persuasive, sensual, impulsive, free to experience",
    "16/7":"16/7 Karmic Number. Seven: serious, specialist, perfectionist, elegant, superior, knowledgeable, thinker, observant, solitary, eccentric, secretive, skeptic, wizard, magician, quiet, refined, intellectual, studious, cautious, analytical, deep, selective",
    "19/1":"19/1 Karmic Number. One: Decisive, courageous, leader, honest, active, dynamic, witty, impatient, innovative, independent, assertive, original, quick, inventive, mental, strong, principled"
    },
  "heartsDesire":{"label":"Heart’s Desire: You really want to be",
    "0":"",
    "1":"One: Decisive, courageous, leader, honest, active, dynamic, witty, impatient, innovative, independent, assertive, original, quick, inventive, mental, strong, principled",
    "2":"Two: Cooperative, tactful, patient, humble, collaborative, understanding, timid, indecisive, sensitive, supportive, unassuming, diplomatic, quiet, listener",
    "3":"Three: expressive, social, charming, visionary, friendly, joyful, scattered, easygoing, joking, pleasure loving, artistic, optimistic, imaginative, gregarious, fun loving, persuasive, dramatic, generous",
    "4":"Four: traditional, conservative, reliable, focused, disciplined, quiet, cautious, quiet, systematic, stubborn, practical, sensible, rational, honest, realistic, loyal, hardworking, serious",
    "5":"Five: nonconforming, active, versatile, flirtatious, speedy, clever, gregarious, enthusiastic, magnetic, impulsive, competitive, affectionate, adventurous, quick, different, charismatic, persuasive, sensual, impulsive, reckless",
    "6":"Six: domestic, nurturing, teacher, counselor, conventional, moral, consistent, generous, loyal, determined, compromising, judgmental, responsible, care giver, friendly, dependable, loving, practical, traditional, addictive",
    "7":"Seven: serious, specialist, perfectionist, elegant, superior, knowledgeable, thinker, aloof, solitary, eccentric, secretive, skeptic, wizard, magician, quiet, refined, intellectual, studious, cautious, analytical, deep, selective",
    "8":"Eight: Strong, forceful, money minded, decisive, authoritative, professional, blunt, masterful, problem solver, spiritual, demanding, powerful, ambitious, conservative, confident, efficient, formal, discerning, reliable",
    "9":"Nine: philosophical, wise, dramatic, religious, lover, tolerant, resourceful, intuitive, powerful, aloof, detached, fortunate, humanitarian, dreamer, poetic, generous, universal, dynamic, evolved, impressionable, global, distant",
    "11/2":"Eleven: inspirational, poetic, romantic, refined, aesthetic, famous, feminine, passive, intense, eccentric, fussy, worrisome, sensitive, achiever, celebrity, enthusiastic, idealistic, spiritual, imaginative, intuitive",
    "22/4":"Twenty two: masterful, builder, mission driven, intuitive, competent, visionary, efficient, expert, honest, hardworking, rational, leader, practical, spiritual, accomplished, powerful, assured, confident, worrisome",
    "33/6":"Thirty three: compassionate, teacher, wise, loving, caring, healer, care giver, judgmental, impulsive, visionary, creative, generous, creative, imaginative, playful, optimistic, friendly, storyteller, community builder",
      "13/4":"13/4 Karmic Number. Four: traditional, conservative, reliable, focused, disciplined, quiet, cautious, quiet, systematic, stubborn, practical, sensible, rational, honest, realistic, loyal, hardworking, serious",
    "14/5":"14/5 Karmic Number. Five: nonconforming, active, versatile, flirtatious, speedy, clever, gregarious, enthusiastic, magnetic, impulsive, competitive, affectionate, adventurous, quick, different, charismatic, persuasive, sensual, impulsive",
    "16/7":"16/7 Karmic Number. Seven: serious, specialist, perfectionist, elegant, superior, knowledgeable, thinker, aloof, solitary, eccentric, secretive, skeptic, wizard, magician, quiet, refined, intellectual, studious, cautious, analytical, deep, selective",
    "19/1":"19/1 Karmic Number. One: Decisive, courageous, leader, honest, active, dynamic, witty, impatient, innovative, independent, assertive, original, quick, inventive, mental, strong, principled"
    },
  "personality":{"label":"Personality: How others see you",
    "0":"",
    "1":"One: Decisive, courageous, leader, honest, active, dynamic, witty, impatient, innovative, independent, assertive, original, quick, inventive, mental, strong, principled",
    "2":"Two: Cooperative, tactful, patient, self-effacing, collector, understanding, timid, indecisive, sensitive, supportive, unassuming, diplomatic, quiet, listener",
    "3":"Three: expressive, social, charming, visionary, friendly, joyful, scattered, easygoing, joking, pleasure loving, artistic, optimistic, imaginative, gregarious, fun loving, persuasive, dramatic, generous",
    "4":"Four: traditional, conservative, reliable, focused, disciplined, quiet, cautious, quiet, systematic, stubborn, practical, sensible, rational, honest, realistic, loyal, hardworking, serious",
    "5":"Five: nonconforming, active, versatile, flirtatious, speedy, clever, gregarious, enthusiastic, magnetic, impulsive, competitive, affectionate, adventurous, quick, different, charismatic, persuasive, sensual, impulsive",
    "6":"Six: domestic, nurturing, teacher, counselor, conventional, moral, consistent, generous, loyal, determined, compromising, judgmental, responsible, care giver, friendly, dependable, loving, practical, traditional",
    "7":"Seven: serious, specialist, perfectionist, elegant, superior, knowledgeable, thinker, aloof, solitary, eccentric, secretive, skeptic, wizard, magician, quiet, refined, intellectual, studious, cautious, analytical, deep, selective",
    "8":"Eight: Strong, forceful, money minded, decisive, authoritative, professional, blunt, masterful, problem solver, spiritual, demanding, powerful, ambitious, conservative, confident, efficient, formal, discerning, reliable",
    "9":"Nine: philosophical, wise, dramatic, religious, lover, tolerant, resourceful, intuitive, powerful, aloof, detached, fortunate, humanitarian, dreamer, poetic, generous, universal, dynamic, evolved, impressionable, global, distant",
    "11/2":"Eleven: inspirational, poetic, romantic, refined, aesthetic, famous, feminine, passive, intense, eccentric, fussy, worrisome, sensitive, achiever, celebrity, enthusiastic, idealistic, spiritual, imaginative, intuitive",
    "22/4":"Twenty two: masterful, builder, mission driven, intuitive, competent, visionary, efficient, expert, honest, hardworking, rational, leader, practical, spiritual, accomplished, powerful, assured, confident, worrisome",
    "33/6":"Thirty three: compassionate, teacher, wise, loving, caring, healer, care giver, judgmental, impulsive, visionary, creative, generous, creative, imaginative, playful, optimistic, friendly, storyteller, community builder",
       "13/4":"13/4 Karmic Number. Four: traditional, conservative, reliable, focused, disciplined, quiet, cautious, quiet, systematic, stubborn, practical, sensible, rational, honest, realistic, loyal, hardworking, serious",
    "14/5":"14/5 Karmic Number. Five: nonconforming, active, versatile, flirtatious, speedy, clever, gregarious, enthusiastic, magnetic, impulsive, competitive, affectionate, adventurous, quick, different, charismatic, persuasive, sensual, impulsive",
    "16/7":"16/7 Karmic Number. Seven: serious, specialist, perfectionist, elegant, superior, knowledgeable, thinker, aloof, solitary, eccentric, secretive, skeptic, wizard, magician, quiet, refined, intellectual, studious, cautious, analytical, deep, selective",
    "19/1":"19/1 Karmic Number. One: Decisive, courageous, leader, honest, active, dynamic, witty, impatient, innovative, independent, assertive, original, quick, inventive, mental, strong, principled"
    },
  "habitChallenge":{"label":"Habit Challenge: Stress causes you to",
    "0":"",
    "1":"One:  agitated, unrealistic, victim, over confident",
    "2":"Two:  shy, scared, withdrawn, helpless",
    "3":"Three:  Scattered, talkative, over optimistic, frivolous",
    "4":"Four:  stubborn, self-righteous, fixed mindset, narrow vision",
    "5":"Five:  unstable, restless, impatience, impetuous",
    "6":"Six:  justified, corrective, unsolicited advice, argumentative",
    "7":"Seven:  analytical, critical, suspicious, shut down",
    "8":"Eight:  bossy, dominate, directive, forceful",
    "9":"Nine:  impractical, dreamer, detached, over generous",
    "11/2":"11/2 Master Number. Two:  shy, scared, withdrawn, helpless",
    "22/4":"22/4 Master Number. Four:  stubborn, self-righteous, fixed mindset, narrow vision",
    "33/6":"33/6 Six:  justified, corrective, unsolicited advice, argumentative",
    "13/4":"13/4 Karmic Number. Four:  stubborn, self-righteous, fixed mindset, narrow vision",
    "14/5":"14/5 Karmic Number. Five:  unstable, restless, impatience, impetuous",
    "16/7":"16/7 Karmic Number. Seven:  analytical, critical, suspicious, shut down",
    "19/1":"19/1 Karmic Number. One:  agitated, unrealistic, victim, over confident"
    },

  "physicalPlane":{"label":"Physical Plane",
    "0":"",
    "1":"One: Inventive, enthusiastic, active, independent, opinionated, innovative, courageous, spontaneous.",
    "2":"Two: Quiet, sensitive, task-oriented, persevering, reliable, collector, self-conscious, worrier, home-body, supportive, helpful.",
    "3":"Three: Outgoing, gregarious, in-the-moment, creative, traveler, social butterfly, happy, optimistic, generous, sarcastic, witty, recuperate easily.",
    "4":"Four: Practical, organized, likes routine, hard worker, planner, list maker, frugal, punctual, reliable, stubborn, teacher, efficient, self-righteous.",
    "5":"Five: Active, impulsive, speedy, indulgent, impatient, creative, likes change, competitive, athletic, curious, adventurous, unconventional, daring.",
    "6":"Six: Nurturer, sympathetic, problem solver, counselor, responsible, serves others. Does well in fashion, cosmetics, interior design or teaching.",
    "7":"Seven: Refined, good taste, eccentric, analytical, perceptive, academic, hobbiest. Does well in technical, scientific, or spiritual fields.",
    "8":"Eight: Professional, ambitious, strong, works well with money, expensive taste and lifestyle, hard worker, high standards.",
    "9":"Nine: Empowered, expressive, dramatic flair, distant, uncertain, generous, loving, impulsive, extravagant, romantic, dreamer, gullible. Does well in fields dealing with large groups of people.",
    "11/2":"11/2 Master Number. Two: Quiet, sensitive, task-oriented, persevering, reliable, collector, self-conscious, worrier, home-body, supportive, helpful",
    "22/4":"22/4 Master Number. Four: Practical, organized, likes routine, hard worker, planner, list maker, frugal, punctual, reliable, stubborn, teacher,. efficient, self-righteous.",
    "33/6":"33/6 Master Number. Six: Nurturer, sympathetic, problem solver, counselor, responsible, serves others. Does well in fashion, cosmetics, interior design or teaching.",
    "13/4":"13/4 Karmic Number. Four: Practical, organized, likes routine, hard worker, planner, list maker, frugal, punctual, reliable, stubborn, teacher, efficient, self-righteous.",
    "14/5":"14/5 Karmic Number. Five: Active, impulsive, speedy, indulgent, impatient, creative, likes change, competitive, athletic, curious, adventurous, unconventional, daring.",
    "16/7":"16/7 Karmic Number. Seven: Refined, good taste, eccentric, analytical, perceptive, academic, hobbiest. Does well in technical, scientific, or spiritual fields.",
    "19/1":"19/1 Karmic Number. One: Inventive, enthusiastic, active, independent, opinionated, innovative, courageous, spontaneous."
    },
  "mentalPlane":{"label":"Mental Plane",
    "0":"",
    "1":"One: Flashes of inspiration, quick comprehension, high principles, honest, outspoken, witty, original, impatient, innovative.",
    "2":"Two:Exceptional memory, perfectionist, gracious, sensitive to other's opinions, good at organizing and analyzing information.",
    "3":"Three: Creative, optimistic, social, learn from experience, keeps up with current fashions, social and psychological trends, needs recreation and hobbies.",
    "4":"Four: Planner, careful, excellent manager, business owner, does well in fields like surveying, construction, accounting or cost analysis.",
    "5":"Five: Curious, innovative, attracted to the avant-garde, rebel, loves to learn.",
    "6":"Six: Mature, responsible, problem solver, rescues people, worrier, obligated, teacher, counselor, martyr, volunteer, humanitarian.",
    "7":"Seven: Deep thinker, loner, researcher, diagnostician, eccentric, strong intuition, has mathematical or technical skills.",
    "8":"Eight: Problem solver, mathematical thinker, likes large projects, craves recognition, seeks status, enjoys belonging to groups or organizations.",
    "9":"Nine: Attuned to the universal needs of mankind, can anticipate fads or trends, does well working for the good of others, healing presence.",
    "11/2":"11/2 Master Number. Two:Exceptional memory, perfectionist, gracious, sensitive to other's opinions, good at organizing and analyzing information.",
    "22/4":"22/4 Master Number. Four: Planner, careful, excellent manager, business owner, does well in fields like surveying, construction, accounting or cost analysis.",
    "33/6":"33/6 Master Number. Six: Mature, responsible, problem solver, rescues people, worrier, obligated, teacher, counselor, martyr, volunteer, humanitarian.",
    "13/4":"13/4 Karmic Number. Four: Planner, careful, excellent manager, business owner, does well in fields like surveying, construction, accounting or cost analysis.",
    "14/5":"14/5 Karmic Number. Five: Curious, innovative, attracted to the avant-garde, rebel, loves to learn.",
    "16/7":"16/7 Karmic Number. Seven: Deep thinker, loner, researcher, diagnostician, eccentric, strong intuition, has mathematical or technical skills.",
    "19/1":"19/1 Karmic Number. One: Flashes of inspiration, quick comprehension, high principles, honest, outspoken, witty, original, impatient, innovative."
    },
  "emotionalPlane":{"label":"Emotional Plane",
    "0":"",
    "1":"One: Expressive, admire intelligence, strong reaction to new people, make decisions based on gut reaction.",
    "2":"Two: Sensitive, fearful, worrier, great empathy, rescuer, depressed, anxious, needs external validation, takes things personally, enjoys sharing emotional experiences, enjoys music and the arts.",
    "3":"Three: Enjoys recreation, socializing, gossiping. Good sense of humor, takes chances, happy, optimistic, acts on a whim. Desires popularity and admiration.",
    "4":"Four: Dominates others, works on relationships, responsible, loyal, practical empathy, self-judges, does well as a nurse or counselor.",
    "5":"Five: Strong inner vitality, thrives on activity and change, enjoys diversity, objective, passionate, tends to take contrary view.",
    "6":"Six: Very emotional, affectionate, demonstrative, opinionated, worrier, needs to feel useful and appreciated, poor boundaries with others, does well in health, nutrition, teaching and counseling.",
    "7":"Seven: Deep emotions, needs quiet time, reluctant to share feelings, intuitive, needs to trust hunches, admire culture and refinement.",
    "8":"Eight: Very emotional, keeps tight reign on feelings, expressive, highly motivated, persevering, seeks the best in life, capable of working long hours.",
    "9":"Nine: Capacity to feel deeply, enthusiastic, romantic, flair for extravagance, moody, easily influenced, can relate experiences to higher principles, loves finer things of life.",
    "11/2":"11/2 Master Number. Two: Sensitive, fearful, worrier, great empathy, rescuer, depressed, anxious, needs external validation, takes things personally, enjoys sharing emotional experiences, enjoys music and the arts.",
    "22/4":"22/4 Master Number. Four: Dominates others, works on relationships, responsible, loyal, practical empathy, self-judges, does well as a nurse or counselor.",
    "33/6":"33/6 Master Number. Six: Very emotional, affectionate, demonstrative, opinionated, worrier, needs to feel useful and appreciated, poor boundaries with others, does well in health, nutrition, teaching and counseling.",
    "13/4":"13/4 Karmic Number. Four: Dominates others, works on relationships, responsible, loyal, practical empathy, self-judges, does well as a nurse or counselor.",
    "14/5":"14/5 Karmic Number. Five: Strong inner vitality, thrives on activity and change, enjoys diversity, objective, passionate, tends to take contrary view.",
    "16/7":"16/7 Karmic Number. Seven: Deep emotions, needs quiet time, reluctant to share feelings, intuitive, needs to trust hunches, admire culture and refinement.",
    "19/1":"19/1 Karmic Number. One: Expressive, admire intelligence, strong reaction to new people, make decisions based on gut reaction."
    },

  "intuitivePlane":{"label":"Intuitive Plane",
    "0":"",
    "1":"One: Solves problems uniquely, excellent intuition, trust first impressions, enthusiasm can sway others, needs a guiding principle to live by to be happy.",
    "2":"Two: Sensitive, intense convictions, sensitive to other's tragedies, desire to solve others problems.",
    "3":"Three: Excellent psychic, persuasive, optimistic, easily sees humor in situations, sensitive to being considered superficial.",
    "4":"Four: Practical, skeptical, decides based on facts, rationalizes positions, good self-control, objective, careful.",
    "5":"Five: Feels intuition through body with physical symptoms, free thinker, motivated by fear of boredom.",
    "6":"Six: Idealistic, expects much of others, spiritual beliefs are guides to live by, does good works, helps those with emotional ties, anticipates other's needs.",
    "7":"Seven: Extremely intuitive and spiritual, strong moral code, desire to teach, good investigator, easily obtains knowledge.",
    "8":"Eight: Natural leader, confident, good foresight for business, powerful dreams as guides, sees where people fit best in a group.",
    "9":"Nine: Vulnerable, idealistic, highly impressionable, can pull information out of the air, deep interest in religion or metaphysics.",
    "11/2":"11/2 Master Number. Two: Sensitive, intense convictions, sensitive to other's tragedies, desire to solve others problems.",
    "22/4":"22/4 Master Number. Four: Practical, skeptical, decides based on facts, rationalizes positions, good self-control, objective, careful.",
    "33/6":"33/6 Master Number. Six: Idealistic, expects much of others, spiritual beliefs are guides to live by, does good works, helps those with emotional ties, anticipates other's needs.",
    "13/4":"13/4 Karmic Number. Four: Practical, skeptical, decides based on facts, rationalizes positions, good self-control, objective, careful.",
    "14/5":"14/5 Karmic Number. Five: Feels intuition through body with physical symptoms, free thinker, motivated by fear of boredom.",
    "16/7":"16/7 Karmic Number. Seven: Extremely intuitive and spiritual, strong moral code, desire to teach, good investigator, easily obtains knowledge.",
    "19/1":"19/1 Karmic Number. One: Solves problems uniquely, excellent intuition, trust first impressions, enthusiasm can sway others, needs a guiding principle to live by to be happy."
    },

  "personalYear":{"label":"Personal Year:",
    "0":"",
    "1":"Number 1 - BE: Independent, assertive, original, quick, inventive, mental, strong, principled. DO: Start something new, create original ideas, be confident, take a leadership role, look at new aspects of old plans and ideas, be bold, listen to your intuition.",
    "2":"Number 2 - BE: Sensitive, supportive, unassuming, diplomatic, artistic, friendly, quiet, listener. DO: Take time out to rest and recuperate, learn patience, create relationships, be mindful and thoughtful, reflect, observe and experience, ponder your passion & purpose.",
    "3":"Number 3 - BE: Optimistic, imaginative, creative, gregarious, persuasive, dramatic, generous, playful. DO: Travel, play, flirt, be optimistic, entertain, be social, write, sing, draw, and paint. Time to network and market your products and services.",
    "4":"Number 4 - BE: Practical, sensible, rational, honest, realistic, loyal, hardworking, serious. DO: Time to plan your work and work your plan, make commitments and agreements, sign contracts, stay late and finish projects, work pays off with rewards of achievement.",
    "5":"Number 5 - BE: Adventurous, different, charismatic, persuasive, extroverted, sensual, impulsive, rebellious. DO: Expect change to show up unannounced, surprises may catch you off guard, be flexible and adaptable, travel, be dynamic, promote your products and services, you are magnetic.",
    "6":"Number 6 - BE: Responsible, care-giver, artistic, friendly, dependable, loving, practical, traditional. DO: Do domestic activities, spend time with family and friends, family and friends may demand more of your time, set boundaries, create more balance in your life, let your heart shine, people want to be with you now.",
    "7":"Number 7 - BE: Reserved, refined, studious, cautious, analytical, deep, selective, mystical. DO: Time to look for answers within, strong Spiritual connections, fate is at work now, meditate, journal, take a trip to reflect on who you are being.",
    "8":"Number 8 - BE: Powerful, ambitious, conservative, confident, efficient, formal, discerning, focused. DO: Excellent year for business and finance, be forceful to create win-win outcomes, apply yourself to the maximum, work with large projects and businesses.",
    "9":"Number 9 - BE: Humanitarian, dreamer, romantic, generous, evolved, impressionable, sensitive, dramatic. DO: Completion and transition are the key words, out with the old and make room for the new, think global, listen, share, reflect, respond, give, surrender, let go let GOD.",
    "11/2":"11/2 Master Number. Number 2 - BE: Sensitive, supportive, unassuming, diplomatic, artistic, friendly, quiet, listener. DO: Take time out to rest and recuperate, learn patience, create relationships, be mindful and thoughtful, reflect, observe and experience, ponder your passion & purpose.",
    "22/4":"22/4 Master Number. Number 4 - BE: Practical, sensible, rational, honest, realistic, loyal, hardworking, serious. DO: Time to plan your work and work your plan, make commitments and agreements, sign contracts, stay late and finish projects, work pays off with rewards of achievement.",
    "33/6":"33/6 Master Number. Number 6 - BE: Responsible, care-giver, artistic, friendly, dependable, loving, practical, traditional. DO: Do domestic activities, spend time with family and friends, family and friends may demand more of your time, set boundaries, create more balance in your life, let your heart shine, people want to be with you now.",
    "13/4":"13/4 Karmic Number. Number 4 - BE: Practical, sensible, rational, honest, realistic, loyal, hardworking, serious. DO: Time to plan your work and work your plan, make commitments and agreements, sign contracts, stay late and finish projects, work pays off with rewards of achievement.",
    "14/5":"14/5 Karmic Number. Number 5 - BE: Adventurous, different, charismatic, persuasive, extroverted, sensual, impulsive, rebellious. DO: Expect change to show up unannounced, surprises may catch you off guard, be flexible and adaptable, travel, be dynamic, promote your products and services, you are magnetic.",
    "16/7":"16/7 Karmic Number. Number 7 - BE: Reserved, refined, studious, cautious, analytical, deep, selective, mystical. DO: Time to look for answers within, strong Spiritual connections, fate is at work now, meditate, journal, take a trip to reflect on who you are being.",
    "19/1":"19/1 Karmic Number. Number 1 - BE: Independent, assertive, original, quick, inventive, mental, strong, principled. DO: Start something new, create original ideas, be confident, take a leadership role, look at new aspects of old plans and ideas, be bold, listen to your intuition."
    },
  "personalMonth":{"label":"Personal Month:",
    "0":"",
    "1":"Number 1 - BE: Independent, assertive, original, quick, inventive, mental, strong, principled. DO: Start something new, create original ideas, be confident, take a leadership role, look at new aspects of old plans and ideas, be bold, listen to your intuition.",
    "2":"Number 2 - BE: Sensitive, supportive, unassuming, diplomatic, artistic, friendly, quiet, listener. DO: Take time out to rest and recuperate, learn patience, create relationships, be mindful and thoughtful, reflect, observe and experience, ponder your passion & purpose.",
    "3":"Number 3 - BE: Optimistic, imaginative, creative, gregarious, persuasive, dramatic, generous, playful. DO: Travel, play, flirt, be optimistic, entertain, be social, write, sing, draw, and paint. Time to network and market your products and services.",
    "4":"Number 4 - BE: Practical, sensible, rational, honest, realistic, loyal, hardworking, serious. DO: Time to plan your work and work your plan, make commitments and agreements, sign contracts, stay late and finish projects, work pays off with rewards of achievement.",
    "5":"Number 5 - BE: Adventurous, different, charismatic, persuasive, extroverted, sensual, impulsive, rebellious. DO: Expect change to show up unannounced, surprises may catch you off guard, be flexible and adaptable, travel, be dynamic, promote your products and services, you are magnetic.",
    "6":"Number 6 - BE: Responsible, care-giver, artistic, friendly, dependable, loving, practical, traditional. DO: Do domestic activities, spend time with family and friends, family and friends may demand more of your time, set boundaries, create more balance in your life, let your heart shine, people want to be with you now.",
    "7":"Number 7 - BE: Reserved, refined, studious, cautious, analytical, deep, selective, mystical. DO: Time to look for answers within, strong Spiritual connections, fate is at work now, meditate, journal, take a trip to reflect on who you are being.",
    "8":"Number 8 - BE: Powerful, ambitious, conservative, confident, efficient, formal, discerning, focused. DO: Excellent month for business and finance, be forceful to create win-win outcomes, apply yourself to the maximum, work with large projects and businesses.",
    "9":"Number 9 - BE: Humanitarian, dreamer, romantic, generous, evolved, impressionable, sensitive, dramatic. DO: Completion and transition are the key words, out with the old and make room for the new, think global, listen, share, reflect, respond, give, surrender, let go let GOD.",
    "11/2":"11/2 Master Number. Number 2 - BE: Sensitive, supportive, unassuming, diplomatic, artistic, friendly, quiet, listener. DO: Take time out to rest and recuperate, learn patience, create relationships, be mindful and thoughtful, reflect, observe and experience, ponder your passion & purpose.",
    "22/4":"22/4 Master Number. Number 4 - BE: Practical, sensible, rational, honest, realistic, loyal, hardworking, serious. DO: Time to plan your work and work your plan, make commitments and agreements, sign contracts, stay late and finish projects, work pays off with rewards of achievement.",
    "33/6":"33/6 Master Number. Number 6 - BE: Responsible, care-giver, artistic, friendly, dependable, loving, practical, traditional. DO: Do domestic activities, spend time with family and friends, family and friends may demand more of your time, set boundaries, create more balance in your life, let your heart shine, people want to be with you now.",
    "13/4":"13/4 Karmic Number. Number 4 - BE: Practical, sensible, rational, honest, realistic, loyal, hardworking, serious. DO: Time to plan your work and work your plan, make commitments and agreements, sign contracts, stay late and finish projects, work pays off with rewards of achievement.",
    "14/5":"14/5 Karmic Number. Number 5 - BE: Adventurous, different, charismatic, persuasive, extroverted, sensual, impulsive, rebellious. DO: Expect change to show up unannounced, surprises may catch you off guard, be flexible and adaptable, travel, be dynamic, promote your products and services, you are magnetic.",
    "16/7":"16/7 Karmic Number. Number 7 - BE: Reserved, refined, studious, cautious, analytical, deep, selective, mystical. DO: Time to look for answers within, strong Spiritual connections, fate is at work now, meditate, journal, take a trip to reflect on who you are being.",
    "19/1":"19/1 Karmic Number. Number 1 - BE: Independent, assertive, original, quick, inventive, mental, strong, principled. DO: Start something new, create original ideas, be confident, take a leadership role, look at new aspects of old plans and ideas, be bold, listen to your intuition."
    },
  "personalDay":{"label":"Personal Day:",
    "0":"",
    "1":"One: Great day for major decisions, new moves and alliances, starting a job, taking a trip with a purpose.  Be honest, assertive, and aim for the top.  A good day for major surgery.",
    "2":"Two: Good day for quiet pursuits, friendships, dates, and meetings.  Wait patiently; study, be especially cooperative; focus on details.  Don't push. Good for a quiet marriage celebration.  Avoid surgery.",
    "3":"Three: A fun day. Good for asking favors. Throw a party. Take a short business trip. Favorable for surgery. Try your luck at the races.  Watch extravagances.",
    "4":"Four: Good for business planning, but not for travel. See your lawyer; undertake money or investment transactions, understand all contracts fully. Go ahead with marriage but watch for complications.  Medical treatments and routine surgery are fine.",
    "5":"Five: A great day for public speaking, networking, partying, and promotion.  Spontaneous start to a trip.  Be aware of possible changes or surprises.  Note the best day for a wedding. Better day for an affair.",
    "6":"Six: Good wedding aspects; great for family reunions or to greet an adopted child.  Divorce proceedings favored.  Avoid heated arguments about petty issues.  Not ideal for travel.  May inherit money.  Health checkups are a good idea.  Do not avoid being alone.",
    "7":"Seven: Good for walks by the sea.  Spend 10 minutes in the morning collecting your thoughts.  Avoid surgery; expect delays.  Do not take an assertive stance.  Do not become frustrated or suicidal because the car won't start.",
    "8":"Eight: A good day to buy or sell property.  All financial matters are favored with clear contracts. Travel on business but for a vacation. Be particularly well-dressed, put on your most authoritative manner.  Present reasons for a raise.",
    "9":"Nine: A wonderful day to spend with friends, working with disadvantaged people, or making hospital visits. Postpone major surgery.  Good for a long-awaited marriage or long-distance flights.  Be especially generous, tolerant, and loving. Avoid dwelling on problems.  Realize tomorrow is another (ONE) day.",
    "11/2":"",
    "22/4":"",
    "33/6":"",
    "13/4":"",
    "14/5":"",
    "16/7":"",
    "19/1":""
    },
  "firstLabel":{"label":"Age of Identity",
    "":"First: In your first age, you are creating your identity."
    },
  "firstPinnacle":{"label":"Pinnacles: Events and Environments",
    "0":"",
    "1":"One:  You are developing your confidence, you are involved in new experiences and ideas, and you tend to go your own way in life. You are learning self-reliance.",
    "2":"Two:  You are sensitive and supportive of people; you are learning the art and science of having patience. Interacting with people is very important to you. You are developing your understanding of spaces and timing.",
    "3":"Three:  You learning to be expressive, you are finding your voice; you are developing your artistic abilities. This is an easy time in your life being social and having fun. Creativity is very important.",
    "4":"Four:  You are learning about responsibility and order. This is a serious time in your life. You may feel a need to marry and build or buy a home. You feel like you must get your work completed.",
    "5":"Five:  You are flying by the seat of your pants, you love to travel and explore, and your curious mind draws you into unusual experiences. You may find yourself being drawn into a career where you are selling and or promoting yourself or products.",
    "6":"Six:  You will find yourself wanting to help and teach others. You feel responsible to do the right thing, this is a strong draw to marry and raise a family. You take on a role of service to your friends, family, and community. You develop a sense of justice.",
    "7":"Seven:  You will find yourself wanting to spend more time alone. You have a strong curiosity to study information about the unseen world. You may find yourself so interested in a subject that you may become an expert in that field of interest.",
    "8":"Eight:  You will find yourself gaining confidence in the world of business. You have a strong need to excel and manifest. You are in the energy of management and organization. Now is the ideal time to manage and grow your business to achieve success.",
    "9":"Nine:  You are learning the importance of staying present. You are spending too much time daydreaming and fantasying about the way your life should be lived. You have a strong desire to help the needy; you may find yourself volunteering. You are also drawn to travel globally; you have a strong interest in humanity.",
    "11/2":"11/2:  You have a heightened sense of intuition, you are being asked to listen to your intuition and develop your sense of purpose. You become excited to explore the mysteries of the universe and share your knowledge.",
    "22/4":"22/4:  You have a heightened sense of responsibility and you know there is something you must accomplish in your lifetime.",
    "33/6":"33/6:   You have a strong desire to save the world, to heal the suffering. You may want to start a movement to rid the world of hunger. You may feel like you want to open a healing center. You have a strong sense of purpose.",
    "13/4":"13/4 Karmic Number. You are learning about responsibility and order. This is a serious time in your life. You may feel a need to marry and build or buy a home. You feel like you must get your work completed.",
    "14/5":"14/5 Karmic Number. You are flying by the seat of your pants, you love to travel and explore, and your curious mind draws you into unusual experiences. You may find yourself being drawn into a career where you are selling and or promoting yourself or products.",
    "16/7":"16/7 Karmic Number.You will find yourself wanting to spend more time alone. You have a strong curiosity to study information about the unseen world. You may find yourself so interested in a subject that you may become an expert in that field of interest. ",
    "19/1":"19/1 Karmic Number. You are developing your confidence, you are involved in new experiences and ideas, and you tend to go your own way in life. You are learning self-reliance."
    },
  "firstChallenge":{"label":"Challenges: Inner Limitations",
    "0":"Zero:  Metaphysics teach that you create your own challenges. If you have a zero challenge at this time, it tells you that you have no outside challenges at this time in your life. If you find challenges, you need to own up to the source. . . YOU!",
    "1":"One:  You are learning survival skills. You may have a strong dominate parent that challenges you. You are learning to trust yourself. You may be dealing with handling some issues around your anger and quick temper.",
    "2":"Two:  Relationships are your teachers; you may be challenged to understand how to be in a happy, healthy relationship. You may find yourself frustrated with having to wait for others. You may not understand how to be a good partner.",
    "3":"Three:  You may not feel it is important to express yourself. You are challenged to communicate your feelings. You have a difficult time believing you have any creative abilities.",
    "4":"Four:  You feel trapped and restricted with routines and systems you are involved with. You have a difficult time following the rules; you don’t seem to be able to get out of the ruts you may have created.",
    "5":"Five:  You are restless and have a difficult time staying focused and completing tasks and projects. Your avant-guard attitude gets you into trouble. You feel trapped and crave freedom.",
    "6":"Six:  You may find that your commitments have caused you to become over loaded with responsibility. Your friends and family responsibilities may seem to consume too much of your personal time.",
    "7":"Seven:  You may find you have trust issues with people. You will be drawn to spend time alone with your thoughts. You may find yourself becoming isolated and or lonely. Superficial conversations bore you.",
    "8":"Eight:  You may find yourself spending lots of time at work. You are driven to accomplish and produce. You have a passion to create wealth at all costs. You may find yourself dominating your fellow workers if they can’t keep up the pace.",
    "9":""
    },

  "secondLabel":{"label":"Age of Life Skills",
    "":"Second: In your second age, you are building your life skills."
    },
  "secondPinnacle":{"label":"Pinnacles: Events and Environments",
    "0":"",
    "1":"One:  You are developing your confidence, you are involved in new experiences and ideas, and you tend to go your own way in life. You are learning self-reliance.",
    "2":"Two:  You are sensitive and supportive of people; you are learning the art and science of having patience. Interacting with people is very important to you. You are developing your understanding of spaces and timing.",
    "3":"Three:  You learning to be expressive, you are finding your voice; you are developing your artistic abilities. This is an easy time in your life being social and having fun. Creativity is very important.",
    "4":"Four:  You are learning about responsibility and order. This is a serious time in your life. You may feel a need to marry and build or buy a home. You feel like you must get your work completed.",
    "5":"Five:  You are flying by the seat of your pants, you love to travel and explore, and your curious mind draws you into unusual experiences. You may find yourself being drawn into a career where you are selling and or promoting yourself or products.",
    "6":"Six:  You will find yourself wanting to help and teach others. You feel responsible to do the right thing, this is a strong draw to marry and raise a family. You take on a role of service to your friends, family, and community. You develop a sense of justice.",
    "7":"Seven:  You will find yourself wanting to spend more time alone. You have a strong curiosity to study information about the unseen world. You may find yourself so interested in a subject that you may become an expert in that field of interest.",
    "8":"Eight:  You will find yourself gaining confidence in the world of business. You have a strong need to excel and manifest. You are in the energy of management and organization. Now is the ideal time to manage and grow your business to achieve success.",
    "9":"Nine:  You are learning the importance of staying present. You are spending too much time daydreaming and fantasying about the way your life should be lived. You have a strong desire to help the needy; you may find yourself volunteering. You are also drawn to travel globally; you have a strong interest in humanity.",
    "11/2":"11/2:  You have a heightened sense of intuition, you are being asked to listen to your intuition and develop your sense of purpose. You become excited to explore the mysteries of the universe and share your knowledge.",
    "22/4":"22/4:  You have a heightened sense of responsibility and you know there is something you must accomplish in your lifetime.",
    "33/6":"33/6:   You have a strong desire to save the world, to heal the suffering. You may want to start a movement to rid the world of hunger. You may feel like you want to open a healing center. You have a strong sense of purpose.",
    "13/4":" 13/4 Karmic Number. You are learning about responsibility and order. This is a serious time in your life. You may feel a need to marry and build or buy a home. You feel like you must get your work completed.",
    "14/5":"14/5 Karmic Number. You are flying by the seat of your pants, you love to travel and explore, and your curious mind draws you into unusual experiences. You may find yourself being drawn into a career where you are selling and or promoting yourself or products",
    "16/7":"16/7 Karmic Number. You will find yourself wanting to spend more time alone. You have a strong curiosity to study information about the unseen world. You may find yourself so interested in a subject that you may become an expert in that field of interest.",
    "19/1":"19/1 Karmic Number. You are developing your confidence, you are involved in new experiences and ideas, and you tend to go your own way in life. You are learning self-reliance."
    },
  "secondChallenge":{"label":"Challenges: Inner Limitations",
    "0":"Zero:  Metaphysics teach that you create your own challenges. If you have a zero challenge at this time, it tells you that you have no outside challenges at this time in your life. If you find challenges, you need to own up to the source. . . YOU!",
    "1":"One:  You are learning survival skills. You may have a strong dominate parent that challenges you. You are learning to trust yourself. You may be dealing with handling some issues around your anger and quick temper.",
    "2":"Two:  Relationships are your teachers; you may be challenged to understand how to be in a happy, healthy relationship. You may find yourself frustrated with having to wait for others. You may not understand how to be a good partner.",
    "3":"Three:  You may not feel it is important to express yourself. You are challenged to communicate your feelings. You have a difficult time believing you have any creative abilities.",
    "4":"Four:  You feel trapped and restricted with routines and systems you are involved with. You have a difficult time following the rules; you don’t seem to be able to get out of the ruts you may have created.",
    "5":"Five:  You are restless and have a difficult time staying focused and completing tasks and projects. Your avant-guard attitude gets you into trouble. You feel trapped and crave freedom.",
    "6":"Six:  You may find that your commitments have caused you to become over loaded with responsibility. Your friends and family responsibilities may seem to consume too much of your personal time.",
    "7":"Seven:  You may find you have trust issues with people. You will be drawn to spend time alone with your thoughts. You may find yourself becoming isolated and or lonely. Superficial conversations bore you.",
    "8":"Eight:  You may find yourself spending lots of time at work. You are driven to accomplish and produce. You have a passion to create wealth at all costs. You may find yourself dominating your fellow workers if they can’t keep up the pace.",
    "9":""
    },
  "thirdLabel":{"label":"Age of Purpose & Fulfillment",
    "":"Third: In your third age, you are seeking purpose and fulfillment."
    },
  "thirdPinnacle":{"label":"Pinnacles: Events and Environments",
    "0":"",
    "1":"One:  You are developing your confidence, you are involved in new experiences and ideas, and you tend to go your own way in life. You are learning self-reliance.",
    "2":"Two:  You are sensitive and supportive of people; you are learning the art and science of having patience. Interacting with people is very important to you. You are developing your understanding of spaces and timing.",
    "3":"Three:  You learning to be expressive, you are finding your voice; you are developing your artistic abilities. This is an easy time in your life being social and having fun. Creativity is very important.",
    "4":"Four:  You are learning about responsibility and order. This is a serious time in your life. You may feel a need to marry and build or buy a home. You feel like you must get your work completed.",
    "5":"Five:  You are flying by the seat of your pants, you love to travel and explore, and your curious mind draws you into unusual experiences. You may find yourself being drawn into a career where you are selling and or promoting yourself or products.",
    "6":"Six:  You will find yourself wanting to help and teach others. You feel responsible to do the right thing, this is a strong draw to marry and raise a family. You take on a role of service to your friends, family, and community. You develop a sense of justice.",
    "7":"Seven:  You will find yourself wanting to spend more time alone. You have a strong curiosity to study information about the unseen world. You may find yourself so interested in a subject that you may become an expert in that field of interest.",
    "8":"Eight:  You will find yourself gaining confidence in the world of business. You have a strong need to excel and manifest. You are in the energy of management and organization. Now is the ideal time to manage and grow your business to achieve success.",
    "9":"Nine:  You are learning the importance of staying present. You are spending too much time daydreaming and fantasying about the way your life should be lived. You have a strong desire to help the needy; you may find yourself volunteering. You are also drawn to travel globally; you have a strong interest in humanity.",
    "11/2":"Eleven:  You have a heightened sense of intuition, you are being asked to listen to your intuition and develop your sense of purpose. You become excited to explore the mysteries of the universe and share your knowledge.",
    "22/4":"Twenty-Two:  You have a heightened sense of responsibility and you know there is something you must accomplish in your lifetime.",
    "33/6":"Thirty-Three:   You have a strong desire to save the world, to heal the suffering. You may want to start a movement to rid the world of hunger. You may feel like you want to open a healing center. You have a strong sense of purpose.",
    "13/4":" 13/4 Karmic Number. You are learning about responsibility and order. This is a serious time in your life. You may feel a need to marry and build or buy a home. You feel like you must get your work completed.",
    "14/5":"14/5 Karmic Number. You are flying by the seat of your pants, you love to travel and explore, and your curious mind draws you into unusual experiences. You may find yourself being drawn into a career where you are selling and or promoting yourself or products",
    "16/7":"16/7 Karmic Number. You will find yourself wanting to spend more time alone. You have a strong curiosity to study information about the unseen world. You may find yourself so interested in a subject that you may become an expert in that field of interest.",
    "19/1":"19/1 Karmic Number. You are developing your confidence, you are involved in new experiences and ideas, and you tend to go your own way in life. You are learning self-reliance."
    },
  "thirdChallenge":{"label":"Challenges: Inner Limitations",
    "0":"Zero:  Metaphysics teach that you create your own challenges. If you have a zero challenge at this time, it tells you that you have no outside challenges at this time in your life. If you find challenges, you need to own up to the source. . . YOU!",
    "1":"One:  You are learning survival skills. You may have a strong dominate parent that challenges you. You are learning to trust yourself. You may be dealing with handling some issues around your anger and quick temper.",
    "2":"Two:  Relationships are your teachers; you may be challenged to understand how to be in a happy, healthy relationship. You may find yourself frustrated with having to wait for others. You may not understand how to be a good partner.",
    "3":"Three:  You may not feel it is important to express yourself. You are challenged to communicate your feelings. You have a difficult time believing you have any creative abilities.",
    "4":"Four:  You feel trapped and restricted with routines and systems you are involved with. You have a difficult time following the rules; you don’t seem to be able to get out of the ruts you may have created.",
    "5":"Five:  You are restless and have a difficult time staying focused and completing tasks and projects. Your avant-guard attitude gets you into trouble. You feel trapped and crave freedom.",
    "6":"Six:  You may find that your commitments have caused you to become over loaded with responsibility. Your friends and family responsibilities may seem to consume too much of your personal time.",
    "7":"Seven:  You may find you have trust issues with people. You will be drawn to spend time alone with your thoughts. You may find yourself becoming isolated and or lonely. Superficial conversations bore you.",
    "8":"Eight:  You may find yourself spending lots of time at work. You are driven to accomplish and produce. You have a passion to create wealth at all costs. You may find yourself dominating your fellow workers if they can’t keep up the pace.",
    "9":""
    },
  "fourthLabel":{"label":"Age of Legacy",
    "":"Fourth: In your fourth age, you are looking for ways to give back and to leave a legacy."
    },
  "fourthPinnacle":{"label":"Pinnacles: Events and Environments",
    "0":"",
    "1":"One:  You are developing your confidence, you are involved in new experiences and ideas, and you tend to go your own way in life. You are learning self-reliance.",
    "2":"Two:  You are sensitive and supportive of people; you are learning the art and science of having patience. Interacting with people is very important to you. You are developing your understanding of spaces and timing.",
    "3":"Three:  You learning to be expressive, you are finding your voice; you are developing your artistic abilities. This is an easy time in your life being social and having fun. Creativity is very important.",
    "4":"Four:  You are learning about responsibility and order. This is a serious time in your life. You may feel a need to marry and build or buy a home. You feel like you must get your work completed.",
    "5":"Five:  You are flying by the seat of your pants, you love to travel and explore, and your curious mind draws you into unusual experiences. You may find yourself being drawn into a career where you are selling and or promoting yourself or products.",
    "6":"Six:  You will find yourself wanting to help and teach others. You feel responsible to do the right thing, this is a strong draw to marry and raise a family. You take on a role of service to your friends, family, and community. You develop a sense of justice.",
    "7":"Seven:  You will find yourself wanting to spend more time alone. You have a strong curiosity to study information about the unseen world. You may find yourself so interested in a subject that you may become an expert in that field of interest.",
    "8":"Eight:  You will find yourself gaining confidence in the world of business. You have a strong need to excel and manifest. You are in the energy of management and organization. Now is the ideal time to manage and grow your business to achieve success.",
    "9":"Nine:  You are learning the importance of staying present. You are spending too much time daydreaming and fantasying about the way your life should be lived. You have a strong desire to help the needy; you may find yourself volunteering. You are also drawn to travel globally; you have a strong interest in humanity.",
    "11/2":"Eleven:  You have a heightened sense of intuition, you are being asked to listen to your intuition and develop your sense of purpose. You become excited to explore the mysteries of the universe and share your knowledge.",
    "22/4":"Twenty-Two:  You have a heightened sense of responsibility and you know there is something you must accomplish in your lifetime.",
    "33/6":"Thirty-Three:   You have a strong desire to save the world, to heal the suffering. You may want to start a movement to rid the world of hunger. You may feel like you want to open a healing center. You have a strong sense of purpose.",
    "13/4":" 13/4 Karmic Number. You are learning about responsibility and order. This is a serious time in your life. You may feel a need to marry and build or buy a home. You feel like you must get your work completed.",
    "14/5":"14/5 Karmic Number. You are flying by the seat of your pants, you love to travel and explore, and your curious mind draws you into unusual experiences. You may find yourself being drawn into a career where you are selling and or promoting yourself or products",
    "16/7":"16/7 Karmic Number. You will find yourself wanting to spend more time alone. You have a strong curiosity to study information about the unseen world. You may find yourself so interested in a subject that you may become an expert in that field of interest.",
    "19/1":"19/1 Karmic Number. You are developing your confidence, you are involved in new experiences and ideas, and you tend to go your own way in life. You are learning self-reliance."
    },
  "fourthChallenge":{"label":"Challenges: Inner Limitations",
    "0":"Zero:  Metaphysics teach that you create your own challenges. If you have a zero challenge at this time, it tells you that you have no outside challenges at this time in your life. If you find challenges, you need to own up to the source. . . YOU!",
    "1":"One:  You are learning survival skills. You may have a strong dominate parent that challenges you. You are learning to trust yourself. You may be dealing with handling some issues around your anger and quick temper.",
    "2":"Two:  Relationships are your teachers; you may be challenged to understand how to be in a happy, healthy relationship. You may find yourself frustrated with having to wait for others. You may not understand how to be a good partner.",
    "3":"Three:  You may not feel it is important to express yourself. You are challenged to communicate your feelings. You have a difficult time believing you have any creative abilities.",
    "4":"Four:  You feel trapped and restricted with routines and systems you are involved with. You have a difficult time following the rules; you don’t seem to be able to get out of the ruts you may have created.",
    "5":"Five:  You are restless and have a difficult time staying focused and completing tasks and projects. Your avant-guard attitude gets you into trouble. You feel trapped and crave freedom.",
    "6":"Six:  You may find that your commitments have caused you to become over loaded with responsibility. Your friends and family responsibilities may seem to consume too much of your personal time.",
    "7":"Seven:  You may find you have trust issues with people. You will be drawn to spend time alone with your thoughts. You may find yourself becoming isolated and or lonely. Superficial conversations bore you.",
    "8":"Eight:  You may find yourself spending lots of time at work. You are driven to accomplish and produce. You have a passion to create wealth at all costs. You may find yourself dominating your fellow workers if they can’t keep up the pace.",
    "9":""
    },

  "count1":{"label":"1",
    "0":"You are not confident.",
    "1":"You are not confident.",
    "2":"You have an average amount of confidence.",
    "3":"You have an average amount of confidence.",
    "4":"You are confident; you have a desire to lead.",
    "5":"You are so confident that you don’t listen to others.",
    "6":"You are so confident that you don’t listen to others.",
    "7":"You are so confident that you don’t listen to others.",
    "8":"You are so confident that you don’t listen to others.",
    "9":"You are so confident that you don’t listen to others."
    },
  "count2":{"label":"2",
    "0":"You are impatient and have little follow-through to complete things.",
    "1":"You are patient and will cooperate.",
    "2":"You are patient and will cooperate.",
    "3":"You are patient and will cooperate.",
    "4":"You are patient and will cooperate.",
    "5":"You are patient and will cooperate.",
    "6":"You are patient and will cooperate.",
    "7":"You are patient and will cooperate.",
    "8":"You are patient and will cooperate.",
    "9":"You are patient and will cooperate."
    },
  "count3":{"label":"3",
    "0":"You can be challenged with articulating what you mean.",
    "1":"You can be creative.",
    "2":"You can be creative.",
    "3":"You can be creative.",
    "4":"You have good communication skills; you are optimistic; you are creative.",
    "5":"You have good communication skills; you are optimistic; you are creative.",
    "6":"You have good communication skills; you are optimistic; you are creative.",
    "7":"You have good communication skills; you are optimistic; you are creative.",
    "8":"You have good communication skills; you are optimistic; you are creative.",
    "9":"You have good communication skills; you are optimistic; you are creative."
    },
  "count4":{"label":"4",
    "0":"You are not practical. If 4 is the only missing number, it is a sign of good health.",
    "1":"You are good at implementing other people’s ideas.",
    "2":"You are good at implementing other people’s ideas.",
    "3":"You are extremely practical; you are a hard worker.",
    "4":"You are extremely practical; you are a hard worker.",
    "5":"You are extremely practical; you are a hard worker.",
    "6":"You are extremely practical; you are a hard worker.",
    "7":"You are extremely practical; you are a hard worker.",
    "8":"You are extremely practical; you are a hard worker.",
    "9":"You are extremely practical; you are a hard worker."
    },
  "count5":{"label":"5",
    "0":"You are not competitive or curious.",
    "1":"You are not competitive or curious.",
    "2":"You are not competitive or curious.",
    "3":"You are flexible and adaptable.",
    "4":"You are flexible and adaptable.",
    "5":"You need lots of personal freedom. You have excellent sales ability.",
    "6":"You need lots of personal freedom. You have excellent sales ability.",
    "7":"You need lots of personal freedom. You have excellent sales ability.",
    "8":"You need lots of personal freedom. You have excellent sales ability.",
    "9":"You need lots of personal freedom. You have excellent sales ability."
    },
  "count6":{"label":"6",
    "0":"You will probably marry more than once.",
    "1":"You have good judgment; you rescue people.",
    "2":"You have good judgment; you rescue people.",
    "3":"You are traditional, opinionated, and loyal.",
    "4":"You are traditional, opinionated, and loyal.",
    "5":"You are traditional, opinionated, and loyal.",
    "6":"You are traditional, opinionated, and loyal.",
    "7":"You are traditional, opinionated, and loyal.",
    "8":"You are traditional, opinionated, and loyal.",
    "9":"You are traditional, opinionated, and loyal."
    },
  "count7":{"label":"7",
    "0":"You are open-minded; a tireless worker, you are curious.",
    "1":"You have exceptional memory and a spiritual interest.",
    "2":"You have exceptional memory and a spiritual interest",
    "3":"You are eccentric, analytical and aloof.",
    "4":"You are eccentric, analytical and aloof.",
    "5":"You are eccentric, analytical and aloof.",
    "6":"You are eccentric, analytical and aloof.",
    "7":"You are eccentric, analytical and aloof.",
    "8":"You are eccentric, analytical and aloof.",
    "9":"You are eccentric, analytical and aloof."
    },
  "count8":{"label":"8",
    "0":"People will offer to help you. Money is unimportant to you; it is for the higher purpose. If you are unattached to money it will magically come to you. You do something for the love of doing it not for the money it brings you.",
    "1":"You like to supervise people; you are reliable.",
    "2":"You are extremely hard working; you like to work with money.",
    "3":"You are extremely hard working; you like to work with money.",
    "4":"You are extremely hard working; you like to work with money.",
    "5":"You are extremely hard working; you like to work with money.",
    "6":"You are extremely hard working; you like to work with money.",
    "7":"You are extremely hard working; you like to work with money.",
    "8":"You are extremely hard working; you like to work with money.",
    "9":"You are extremely hard working; you like to work with money."
    },
  "count9":{"label":"9",
    "0":"You have trouble finishing projects.",
    "1":"You are compassionate; have idealistic goals; you enjoy romance.",
    "2":"You are compassionate; have idealistic goals; you enjoy romance.",
    "3":"You are compassionate; have idealistic goals; you enjoy romance.",
    "4":"You are compassionate; have idealistic goals; you enjoy romance.",
    "5":"You are compassionate; have idealistic goals; you enjoy romance.",
    "6":"You are extremely emotional and vulnerable to outside influences. You may be moody. You will do well to be careful about becoming narcissistic.",
    "7":"You are extremely emotional and vulnerable to outside influences. You may be moody. You will do well to be careful about becoming narcissistic.",
    "8":"You are extremely emotional and vulnerable to outside influences. You may be moody. You will do well to be careful about becoming narcissistic.",
    "9":"You are extremely emotional and vulnerable to outside influences. You may be moody. You will do well to be careful about becoming narcissistic."
    },
  "karmicLesson":{"label":"Karmic Lesson",
    "1":"One: Learn to be Independent, develop confidence, become a leader",
    "2":"Two: Learning about relationships will teach you your life lessons",
    "3":"Three: Learn to express your feelings, find your voice, express yourself",
    "4":"Four: Learn to apply yourself, understand structure, focus ",
    "5":"Five: Learn to be flexible and adaptable, take calculated risks",
    "6":"Six: Learn how to set boundaries, learn to receive, learn balance",
    "7":"Seven: Learn to trust, seek to understand the unseen world, develop intuition",
    "8":"Eight: Learn about the energy of money, learn about management energy",
    "9":"Nine: Learn about catch and release, learn about values, learn about reality"    },
  "findInput":{"label":""
    }
    
  };
        
        
/*
  "personalDay":{"label":"Personal Day:",
    "0":"",
    "1":"",
    "2":"",
    "3":"",
    "4":"",
    "5":"",
    "6":"",
    "7":"",
    "8":"",
    "9":"",
    "11/2":"",
    "22/4":"",
    "33/6":"",
    "13/4":"",
    "14/5":"",
    "16/7":"",
    "19/1":""
    },
//unused meta fields
  "firstNameInput":{"label":"First Name"},
  "middleNameInput":{"label":"Middle Name"},
  "lastNameInput":{"label":"Last Name"},
  "birthdayInput":{"label":"Birthday"},
  "dayOfWeek":{"label":""},
  "dayOfYear":{"label":""},
  "firstName":{"label":"First Name"},
  "middleName":{"label":"Middle Name"},
  "lastName":{"label":"Last Name"},

*/