var summaryFields=[

{"type":"heading", "align":"center", "x":6, "y":0, "w":12, "content":"What's My Destiny?"},
{"type":"text", "align":"center", "x":6, "y":1.5, "w":12, "content":"Numerology Delineation For"},
{"type":"boldcalc", "align":"center", "x":6, "y":2.5, "w":12, "content":"fullName"},
{"type":"calc", "align":"center", "x":6, "y":3.5, "w":12, "content":"bornOn"},
{"type":"calc", "align":"center", "x":6, "y":4.5, "w":12, "content":"printedOn"},

{"type":"boldtext", "align":"left", "x":1, "y":6, "w":8, "content":"CORE PERSONALITY ELEMENTS"},
{"type":"text", "align":"left", "x":2.5, "y":7, "w":4.5, "content":"First Name"},
{"type":"value", "align":"left", "x":7.5, "y":7, "w":1, "content":"firstNameVal"},
{"type":"meta", "align":"left", "x":9.5, "y":7, "w":5.5, "content":"firstNameVal"},
{"type":"value", "align":"left", "x":16, "y":7, "w":6, "content":"firstNameInput"},
{"type":"text", "align":"left", "x":2.5, "y":7.5, "w":4.5, "content":"Middle Name"},
{"type":"value", "align":"left", "x":7.5, "y":7.5, "w":1, "content":"middleNameVal"},
{"type":"meta", "align":"left", "x":9.5, "y":7.5, "w":5.5, "content":"middleNameVal"},
{"type":"value", "align":"left", "x":16, "y":7.5, "w":6, "content":"middleNameInput"},
{"type":"text", "align":"left", "x":2.5, "y":8, "w":4.5, "content":"Last Name"},
{"type":"value", "align":"left", "x":7.5, "y":8, "w":1, "content":"lastNameVal"},
{"type":"meta", "align":"left", "x":9.5, "y":8, "w":5.5, "content":"lastNameVal"},
{"type":"value", "align":"left", "x":16, "y":8, "w":6, "content":"lastNameInput"},

{"type":"text", "align":"left", "x":2.5, "y":9, "w":4.5, "content":"Day of Birth"},
{"type":"value", "align":"left", "x":7.5, "y":9, "w":1, "content":"dayOfBirth"},
{"type":"meta", "align":"left", "x":9.5, "y":9, "w":5.5, "content":"dayOfBirth"},
{"type":"text", "align":"left", "x":16, "y":9, "w":6, "content":"Major personality trait"},
{"type":"text", "align":"left", "x":2.5, "y":9.5, "w":4.5, "content":"Birthpath"},
{"type":"value", "align":"left", "x":7.5, "y":9.5, "w":1, "content":"birthpath"},
{"type":"meta", "align":"left", "x":9.5, "y":9.5, "w":5.5, "content":"birthpath"},
{"type":"text", "align":"left", "x":16, "y":9.5, "w":6, "content":"Natural ability/attitudes"},

{"type":"text", "align":"left", "x":2.5, "y":10.5, "w":4.5, "content":"Destiny"},
{"type":"value", "align":"left", "x":7.5, "y":10.5, "w":1, "content":"destiny"},
{"type":"meta", "align":"left", "x":9.5, "y":10.5, "w":5.5, "content":"destiny"},
{"type":"text", "align":"left", "x":16, "y":10.5, "w":6, "content":"Purpose and contribution"},
{"type":"text", "align":"left", "x":2.5, "y":11, "w":4.5, "content":"Realization"},
{"type":"value", "align":"left", "x":7.5, "y":11, "w":1, "content":"realization"},
{"type":"meta", "align":"left", "x":9.5, "y":11, "w":5.5, "content":"realization"},
{"type":"text", "align":"left", "x":16, "y":11, "w":6, "content":"Ultimate achievement"},
{"type":"text", "align":"left", "x":2.5, "y":11.5, "w":4.5, "content":"Heart's Desire"},
{"type":"value", "align":"left", "x":7.5, "y":11.5, "w":1, "content":"heartsDesire"},
{"type":"meta", "align":"left", "x":9.5, "y":11.5, "w":5.5, "content":"heartsDesire"},
{"type":"text", "align":"left", "x":16, "y":11.5, "w":6, "content":"Inner motivation"},
{"type":"text", "align":"left", "x":2.5, "y":12, "w":4.5, "content":"Personality"},
{"type":"value", "align":"left", "x":7.5, "y":12, "w":1, "content":"personality"},
{"type":"meta", "align":"left", "x":9.5, "y":12, "w":5.5, "content":"personality"},
{"type":"text", "align":"left", "x":16, "y":12, "w":6, "content":"Outward appearance"},
{"type":"text", "align":"left", "x":2.5, "y":12.5, "w":4.5, "content":"Habit Challenge"},
{"type":"value", "align":"left", "x":7.5, "y":12.5, "w":1, "content":"habitChallenge"},
{"type":"meta", "align":"left", "x":9.5, "y":12.5, "w":5.5, "content":"habitChallenge"},
{"type":"text", "align":"left", "x":16, "y":12.5, "w":6, "content":"Negative tendencies"},


{"type":"boldtext", "align":"left", "x":1, "y":14, "w":8, "content":"BALANCE OF TEMPERAMENT"},
{"type":"text", "align":"left", "x":2.5, "y":15, "w":4.5, "content":"Physical Response"},
{"type":"value", "align":"left", "x":7.5, "y":15, "w":1, "content":"physicalPlane"},
{"type":"meta", "align":"left", "x":9.5, "y":15, "w":12.5, "content":"physicalPlane"},
{"type":"text", "align":"left", "x":2.5, "y":15.5, "w":4.5, "content":"Mental Response"},
{"type":"value", "align":"left", "x":7.5, "y":15.5, "w":1, "content":"mentalPlane"},
{"type":"meta", "align":"left", "x":9.5, "y":15.5, "w":12.5, "content":"mentalPlane"},
{"type":"text", "align":"left", "x":2.5, "y":16, "w":4.5, "content":"Emotional Response"},
{"type":"value", "align":"left", "x":7.5, "y":16, "w":1, "content":"emotionalPlane"},
{"type":"meta", "align":"left", "x":9.5, "y":16, "w":12.5, "content":"emotionalPlane"},
{"type":"text", "align":"left", "x":2.5, "y":16.5, "w":4.5, "content":"Intuitive Response"},
{"type":"value", "align":"left", "x":7.5, "y":16.5, "w":1, "content":"intuitivePlane"},
{"type":"meta", "align":"left", "x":9.5, "y":16.5, "w":12.5, "content":"intuitivePlane"},


{"type":"boldtext", "align":"left", "x":1, "y":18, "w":8, "content":"SPECIALTIES AND MISSING NUMBERS"},
{"type":"text", "align":"left", "x":2.5, "y":19, "w":4.5, "content":"Distribution of"},
{"type":"text", "align":"left", "x":2.5, "y":19.5, "w":4.5, "content":"Numbers in Name"},

{"type":"text", "align":"center", "x":7, "y":19, "w":1, "content":"1"},
{"type":"valueCount", "align":"center", "x":7, "y":19.5, "w":1, "content":1},
{"type":"text", "align":"center", "x":8, "y":19, "w":1, "content":"2"},
{"type":"valueCount", "align":"center", "x":8, "y":19.5, "w":1, "content":2},
{"type":"text", "align":"center", "x":9, "y":19, "w":1, "content":"3"},
{"type":"valueCount", "align":"center", "x":9, "y":19.5, "w":1, "content":3},
{"type":"text", "align":"center", "x":10, "y":19, "w":1, "content":"4"},
{"type":"valueCount", "align":"center", "x":10, "y":19.5, "w":1, "content":4},
{"type":"text", "align":"center", "x":11, "y":19, "w":1, "content":"5"},
{"type":"valueCount", "align":"center", "x":11, "y":19.5, "w":1, "content":5},
{"type":"text", "align":"center", "x":12, "y":19, "w":1, "content":"6"},
{"type":"valueCount", "align":"center", "x":12, "y":19.5, "w":1, "content":6},
{"type":"text", "align":"center", "x":13, "y":19, "w":1, "content":"7"},
{"type":"valueCount", "align":"center", "x":13, "y":19.5, "w":1, "content":7},
{"type":"text", "align":"center", "x":14, "y":19, "w":1, "content":"8"},
{"type":"valueCount", "align":"center", "x":14, "y":19.5, "w":1, "content":8},
{"type":"text", "align":"center", "x":15, "y":19, "w":1, "content":"9"},
{"type":"valueCount", "align":"center", "x":15, "y":19.5, "w":1, "content":9},

{"type":"text", "align":"center", "x":16, "y":19, "w":4, "content":"Karmic Lessons"},
{"type":"calc", "align":"center", "x":16, "y":19.5, "w":4, "content":"karmicArray"},


{"type":"boldtext", "align":"left", "x":1, "y":21, "w":8, "content":"TRANSITION PERIODS"},

{"type":"text", "align":"right", "x":5.5, "y":22, "w":2.5, "content":"Pinnacles"},
{"type":"text", "align":"right", "x":8.5, "y":22, "w":2.5, "content":"Challenges"},
{"type":"text", "align":"center", "x":12.5, "y":22, "w":2.5, "content":"Ages"},

{"type":"text", "align":"left", "x":2.5, "y":23, "w":2.5, "content":"First:"},
{"type":"value", "align":"right", "x":5.5, "y":23, "w":2.5, "content":"firstPinnacle"},
{"type":"value", "align":"right", "x":8.5, "y":23, "w":2.5, "content":"firstChallenge"},
{"type":"value", "align":"center", "x":12.5, "y":23, "w":2.5, "content":"firstAgeLabel"},
{"type":"text", "align":"left", "x":2.5, "y":23.5, "w":2.5, "content":"Second:"},
{"type":"value", "align":"right", "x":5.5, "y":23.5, "w":2.5, "content":"secondPinnacle"},
{"type":"value", "align":"right", "x":8.5, "y":23.5, "w":2.5, "content":"secondChallenge"},
{"type":"value", "align":"center", "x":12.5, "y":23.5, "w":2.5, "content":"secondAgeLabel"},
{"type":"text", "align":"left", "x":2.5, "y":24, "w":2.5, "content":"Third:"},
{"type":"value", "align":"right", "x":5.5, "y":24, "w":2.5, "content":"thirdPinnacle"},
{"type":"value", "align":"right", "x":8.5, "y":24, "w":2.5, "content":"thirdChallenge"},
{"type":"value", "align":"center", "x":12.5, "y":24, "w":2.5, "content":"thirdAgeLabel"},
{"type":"text", "align":"left", "x":2.5, "y":24.5, "w":2.5, "content":"Fourth:"},
{"type":"value", "align":"right", "x":5.5, "y":24.5, "w":2.5, "content":"fourthPinnacle"},
{"type":"value", "align":"right", "x":8.5, "y":24.5, "w":2.5, "content":"fourthChallenge"},
{"type":"value", "align":"center", "x":12.5, "y":24.5, "w":2.5, "content":"fourthAgeLabel"},

{"type":"text", "align":"right", "x":2.5, "y":26, "w":3, "content":"Personal Year"},
{"type":"value", "align":"right", "x":5.5, "y":26, "w":1, "content":"personalYear"},
{"type":"text", "align":"right", "x":6.5, "y":26, "w":2, "content":"Month"},
{"type":"value", "align":"right", "x":9, "y":26, "w":1, "content":"personalMonth"},

{"type":"text", "align":"left", "x":0, "y":28.25, "w":12, "content":"© 2016 Wes Hamilton"},
{"type":"text", "align":"left", "x":0, "y":29, "w":12, "content":"wes@weshamilton.com"},
{"type":"text", "align":"right", "x":12, "y":28.25, "w":12, "content":"whatsmydestiny.com"},
{"type":"text", "align":"right", "x":12, "y":29, "w":12, "content":"Powered by pixiedustapps.com"}
];



/*
{"type":"", "align":"", "x":, "y":, "w":, "content":""},
*/