
var summaryByFieldValue={

    

  "firstNameVal":{"label":"First Name", 
    "1":"Leader",
    "2":"Partner",
    "3":"Creative",
    "4":"Builder",
    "5":"Adventurer",
    "6":"Teacher",
    "7":"Investigator",
    "8":"Problem Solver",
    "9":"Humanitarian",
    "11/2":"Inspirer",
    "22/4":"Master Builder",
    "33/6":"Master Teacher",
    "13/4":"Karmic Builder",
    "14/5":"Karmic Adventurer",
    "16/7":"Karmic Investigator",
    "19/1":"Karmic Leader"
    },
    
 "middleNameVal":{"label":"Middle Name", 
    "1":"Leader",
    "2":"Partner",
    "3":"Creative",
    "4":"Builder",
    "5":"Adventurer",
    "6":"Teacher",
    "7":"Investigator",
    "8":"Problem Solver",
    "9":"Humanitarian",
    "11/2":"Inspirer",
    "22/4":"Master Builder",
    "33/6":"Master Teacher",
    "13/4":"Karmic Builder",
    "14/5":"Karmic Adventurer",
    "16/7":"Karmic Investigator",
    "19/1":"Karmic Leader"
    },
    
"lastNameVal":{"label":"Last Name", 
    "1":"Leader",
    "2":"Partner",
    "3":"Creative",
    "4":"Builder",
    "5":"Adventurer",
    "6":"Teacher",
    "7":"Investigator",
    "8":"Problem Solver",
    "9":"Humanitarian",
    "11/2":"Inspirer",
    "22/4":"Master Builder",
    "33/6":"Master Teacher",
    "13/4":"Karmic Builder",
    "14/5":"Karmic Adventurer",
    "16/7":"Karmic Investigator",
    "19/1":"Karmic Leader"
    },

  "birthpath":{"label":"Birthpath: I am!",
    "1":"Decisive, Courageous",
    "2":"Cooperative, Tactful",
    "3":"Expressive, Social",
    "4":"Traditional, Conservative",
    "5":"Nonconforming, Active",
    "6":"Domestic, Nurturing",
    "7":"Serious, Specialist",
    "8":"Strong, Forceful",
    "9":"Philosophical, Wise",
    "11/2":"Inspirational, Poetic",
    "22/4":"Masterful, Builder",
    "33/6":"Compassionate, Teacher",
    "13/4":"Creative, Practical",
    "14/5":"Quiet, Charismatic",
    "16/7":"Friendly, Eccentric ",
    "19/1":"Detached, Independent "
    },



  "destiny":{"label":"Destiny:  You must become!",
    "0":"",
    "1":"Decisive, Courageous",
    "2":"Cooperative, Tactful",
    "3":"Expressive, Social",
    "4":"Traditional, Conservative",
    "5":"Nonconforming, Active",
    "6":"Domestic, Nurturing",
    "7":"Serious, Specialist",
    "8":"Strong, Forceful",
    "9":"Philosophical, Wise",
    "11/2":"Inspirational, Poetic",
    "22/4":"Masterful, Builder",
    "33/6":"Compassionate, Teacher",
    "13/4":"Creative, Practical",
    "14/5":"Quiet, Charismatic",
    "16/7":"Friendly, Eccentric ",
    "19/1":"Detached, Independent "
    },
	
	
  "realization":{"label":"Realization: What you will be",
    "0":"",
    "1":"Decisive, Courageous",
    "2":"Cooperative, Tactful",
    "3":"Expressive, Social",
    "4":"Traditional, Conservative",
    "5":"Nonconforming, Active",
    "6":"Domestic, Nurturing",
    "7":"Serious, Specialist",
    "8":"Strong, Forceful",
    "9":"Philosophical, Wise",
    "11/2":"Inspirational, Poetic",
    "22/4":"Masterful, Builder",
    "33/6":"Compassionate, Teacher",
    "13/4":"Creative, Practical",
    "14/5":"Quiet, Charismatic",
    "16/7":"Friendly, Eccentric ",
    "19/1":"Detached, Independent "
    },
	
	
  "heartsDesire":{"label":"Heart’s Desire: You really want to be",
    "0":"",
    "1":"Decisive, Courageous",
    "2":"Cooperative, Tactful",
    "3":"Expressive, Social",
    "4":"Traditional, Conservative",
    "5":"Nonconforming, Active",
    "6":"Domestic, Nurturing",
    "7":"Serious, Specialist",
    "8":"Strong, Forceful",
    "9":"Philosophical, Wise",
    "11/2":"Inspirational, Poetic",
    "22/4":"Masterful, Builder",
    "33/6":"Compassionate, Teacher",
    "13/4":"Creative, Practical",
    "14/5":"Quiet, Charismatic",
    "16/7":"Friendly, Eccentric ",
    "19/1":"Detached, Independent "
    },
	
	
  "personality":{"label":"Personality: How others see you",
    "0":"",
    "1":"Decisive, Courageous",
    "2":"Cooperative, Tactful",
    "3":"Expressive, Social",
    "4":"Traditional, Conservative",
    "5":"Nonconforming, Active",
    "6":"Domestic, Nurturing",
    "7":"Serious, Specialist",
    "8":"Strong, Forceful",
    "9":"Philosophical, Wise",
    "11/2":"Inspirational, Poetic",
    "22/4":"Masterful, Builder",
    "33/6":"Compassionate, Teacher",
    "13/4":"Creative, Practical",
    "14/5":"Quiet, Charismatic",
    "16/7":"Friendly, Eccentric ",
    "19/1":"Detached, Independent "
    },
	
	
  "habitChallenge":{"label":"Habit Challenge: Stress causes you to be",
    "0":"",
    "1":"Agitated, Victim",
    "2":"Shy, Scared",
    "3":"Scattered, Talkative",
    "4":"Stubborn, Self-righteous",
    "5":"Unstable, Restless",
    "6":"Corrective, Argumentative",
    "7":"Analytical, Critical",
    "8":"Bossy, Forceful",
    "9":"Impractical, Detached",
    "11/2":"Sensitive, Fussy",
    "22/4":"Overwhelmed, Shut-down",
    "33/6":"Nosy, Opinionated",
    "13/4":"Meticulous, Distracted",
    "14/5":"Impetuous, Random",
    "16/7":"Martyr, Suspicious",
    "19/1":"Victim, Over-confident"
    },

  "physicalPlane":{"label":"Physical Plane",
    "0":"",
    "1":"Inventive, enthusiastic, active, independent, opinionated, courageous",
    "2":"Quiet, sensitive, task-oriented, persevering, reliable, helpful",
    "3":"Outgoing, gregarious, in-the-moment, creative, traveler, happy",
    "4":"Practical, organized, planner, frugal, punctual, reliable, stubborn",
    "5":"Impulsive, speedy, indulgent, impatient, creative, competitive, daring",
    "6":"Nurturer, sympathetic, problem solver, counselor, responsible",
    "7":"Refined, good taste, eccentric, analytical, perceptive, academic",
    "8":"Professional, ambitious, strong, works well with money, hard worker",
    "9":"Empowered, expressive, dramatic flair, distant, uncertain, generous",
    "11/2":"Master Inspirer, quiet, sensitive, task-oriented, persevering",
    "22/4":"Master Builder, practical, organized, likes routine, hard worker",
    "33/6":"Master Teacher, nurturer, sympathetic, problem solver, responsible",
    "13/4":"Karmic Builder, practical, organized, likes routine, list maker",
    "14/5":"Karmic Change Agent, active, impulsive, speedy, competitive, daring",
    "16/7":"Karmic Relationships, refined, good taste, eccentric, perceptive",
    "19/1":"Karmic Manifester. Inventive, enthusiastic, independent, opinionated"
    },
	
	
  "mentalPlane":{"label":"Mental Plane",
    "0":"",
    "1":"Flashes of inspiration, quick comprehension, high principles, witty",
    "2":"Exceptional memory, perfectionist, sensitive to other's opinions",
    "3":"Creative, optimistic, social, learn from experience, needs hobbies",
    "4":"Planner, careful, excellent manager, business owner",
    "5":"Curious, innovative, attracted to the avant-garde, loves to learn",
    "6":"Mature, responsible, problem solver, rescues people, worrier, obligated",
    "7":"Deep thinker, loner, researcher, diagnostician, eccentric, strong intuition",
    "8":"Problem solver, mathematical thinker, likes large projects, seeks status",
    "9":"Attuned to the universal needs of mankind, can anticipate fads or trends",
    "11/2":"Master Inspirer. Good at organizing and analyzing information",
    "22/4":"Master Builder. Planner, careful, excellent manager, business owner",
    "33/6":"Master Teacher. Mature, responsible, problem solver, rescues people",
    "13/4":"Karmic Builder. Planner, careful, excellent manager, business owner",
    "14/5":"Karmic Change Agent. Curious, innovative, rebel, loves to learn",
    "16/7":"Karmic Relationships. Deep thinker, loner, researcher, eccentric",
    "19/1":"Karmic Manifester. Flashes of inspiration, high principles, honest"
    },
	
	
  "emotionalPlane":{"label":"Emotional Plane",
    "0":"",
    "1":"Expressive, admires intelligence, makes decisions based on gut reaction",
    "2":"Sensitive, fearful, worrier, great empathy, rescuer, depressed, anxious",
    "3":"Enjoys recreation, socializing, acts on a whim, desires popularity",
    "4":"Dominates others, works on relationships, responsible, loyal, self-judges",
    "5":"Strong inner vitality, thrives on activity and change, enjoys diversity",
    "6":"Very emotional, affectionate, demonstrative, opinionated, worrier",
    "7":"Deep emotions, needs quiet time, reluctant to share feelings, intuitive",
    "8":"Very emotional, keeps tight reign on feelings, expressive, highly motivated",
    "9":"Capacity to feel deeply, enthusiastic, romantic, flair for extravagance",
    "11/2":"Master Inspirer. Enjoys sharing emotional experiences, music, and the arts",
    "22/4":"Master Builder. Dominates others, works on relationships, practical empathy",
    "33/6":"Master Teacher. Very emotional, affectionate, demonstrative, opinionated",
    "13/4":"Karmic Builder. Ignores feelings until they blow up, works on relationships",
    "14/5":"Karmic Change Agent. Objective, passionate, tends to take contrary view",
    "16/7":"Karmic Relationships. Deep emotions, reluctant to share feelings, intuitive",
    "19/1":"Karmic Manifester. Expressive, admires intelligence, reacts to new people"
    },

  "intuitivePlane":{"label":"Intuitive Plane",
    "0":"",
    "1":"Solves problems uniquely, excellent intuition, trust first impressions",
    "2":"Sensitive, intense convictions, sensitive to other's tragedies",
    "3":"Excellent psychic, persuasive, optimistic, easily sees humor in situations",
    "4":"Practical, skeptical, decides based on facts, rationalizes positions",
    "5":"Feels intuition through body with physical symptoms, free thinker",
    "6":"Idealistic, spiritual beliefs are guides to live by, anticipates other's needs",
    "7":"Extremely intuitive and spiritual, good investigator, easily obtains knowledge",
    "8":"Good business foresight, powerful dreams as guides, knows how to create teams",
    "9":"Can pull information out of the air, deep interest in religion or metaphysics",
    "11/2":"Master Inspirer. Intense convictions, sensitive to other's tragedies",
    "22/4":"Master Builder. Skeptical, decides based on facts, rationalizes positions",
    "33/6":"Master Teacher. Spiritual beliefs are guides to live by, does good works",
    "13/4":"Karmic Builder. Practical, psychic, skeptical, rationalizes positions",
    "14/5":"Karmic Change Agent. Feels intuition through body with physical symptoms",
    "16/7":"Karmic Relationships. Extremely intuitive and spiritual, accesses knowledge",
    "19/1":"Karmic Manifester. Excellent intuition, needs a guiding principle to be happy"
    },

  "personalYear":{"label":"Personal Year:",
    "0":"",
    "1":"Number 1 - BE: Independent, assertive, original, quick, inventive, mental, strong, principled. DO: Start something new, create original ideas, be confident, take a leadership role, look at new aspects of old plans and ideas, be bold, listen to your intuition.",
    "2":"Number 2 - BE: Sensitive, supportive, unassuming, diplomatic, artistic, friendly, quiet, listener. DO: Take time out to rest and recuperate, learn patience, create relationships, be mindful and thoughtful, reflect, observe and experience, ponder your passion & purpose.",
    "3":"Number 3 - BE: Optimistic, imaginative, creative, gregarious, persuasive, dramatic, generous, playful. DO: Travel, play, flirt, be optimistic, entertain, be social, write, sing, draw, and paint. Time to network and market your products and services.",
    "4":"Number 4 - BE: Practical, sensible, rational, honest, realistic, loyal, hardworking, serious. DO: Time to plan your work and work your plan, make commitments and agreements, sign contracts, stay late and finish projects, work pays off with rewards of achievement.",
    "5":"Number 5 - BE: Adventurous, different, charismatic, persuasive, extroverted, sensual, impulsive, rebellious. DO: Expect change to show up unannounced, surprises may catch you off guard, be flexible and adaptable, travel, be dynamic, promote your products and services, you are magnetic.",
    "6":"Number 6 - BE: Responsible, care-giver, artistic, friendly, dependable, loving, practical, traditional. DO: Do domestic activities, spend time with family and friends, family and friends may demand more of your time, set boundaries, create more balance in your life, let your heart shine, people want to be with you now.",
    "7":"Number 7 - BE: Reserved, refined, studious, cautious, analytical, deep, selective, mystical. DO: Time to look for answers within, strong Spiritual connections, fate is at work now, meditate, journal, take a trip to reflect on who you are being.",
    "8":"Number 8 - BE: Powerful, ambitious, conservative, confident, efficient, formal, discerning, focused. DO: Excellent year for business and finance, be forceful to create win-win outcomes, apply yourself to the maximum, work with large projects and businesses.",
    "9":"Number 9 - BE: Humanitarian, dreamer, romantic, generous, evolved, impressionable, sensitive, dramatic. DO: Completion and transition are the key words, out with the old and make room for the new, think global, listen, share, reflect, respond, give, surrender, let go let GOD.",
    "11/2":"11/2 Master Number. Number 2 - BE: Sensitive, supportive, unassuming, diplomatic, artistic, friendly, quiet, listener. DO: Take time out to rest and recuperate, learn patience, create relationships, be mindful and thoughtful, reflect, observe and experience, ponder your passion & purpose.",
    "22/4":"22/4 Master Number. Number 4 - BE: Practical, sensible, rational, honest, realistic, loyal, hardworking, serious. DO: Time to plan your work and work your plan, make commitments and agreements, sign contracts, stay late and finish projects, work pays off with rewards of achievement.",
    "33/6":"33/6 Master Number. Number 6 - BE: Responsible, care-giver, artistic, friendly, dependable, loving, practical, traditional. DO: Do domestic activities, spend time with family and friends, family and friends may demand more of your time, set boundaries, create more balance in your life, let your heart shine, people want to be with you now.",
    "13/4":"13/4 Karmic Number. Number 4 - BE: Practical, sensible, rational, honest, realistic, loyal, hardworking, serious. DO: Time to plan your work and work your plan, make commitments and agreements, sign contracts, stay late and finish projects, work pays off with rewards of achievement.",
    "14/5":"14/5 Karmic Number. Number 5 - BE: Adventurous, different, charismatic, persuasive, extroverted, sensual, impulsive, rebellious. DO: Expect change to show up unannounced, surprises may catch you off guard, be flexible and adaptable, travel, be dynamic, promote your products and services, you are magnetic.",
    "16/7":"16/7 Karmic Number. Number 7 - BE: Reserved, refined, studious, cautious, analytical, deep, selective, mystical. DO: Time to look for answers within, strong Spiritual connections, fate is at work now, meditate, journal, take a trip to reflect on who you are being.",
    "19/1":"19/1 Karmic Number. Number 1 - BE: Independent, assertive, original, quick, inventive, mental, strong, principled. DO: Start something new, create original ideas, be confident, take a leadership role, look at new aspects of old plans and ideas, be bold, listen to your intuition."
    },
  "personalMonth":{"label":"Personal Month:",
    "0":"",
    "1":"Number 1 - BE: Independent, assertive, original, quick, inventive, mental, strong, principled. DO: Start something new, create original ideas, be confident, take a leadership role, look at new aspects of old plans and ideas, be bold, listen to your intuition.",
    "2":"Number 2 - BE: Sensitive, supportive, unassuming, diplomatic, artistic, friendly, quiet, listener. DO: Take time out to rest and recuperate, learn patience, create relationships, be mindful and thoughtful, reflect, observe and experience, ponder your passion & purpose.",
    "3":"Number 3 - BE: Optimistic, imaginative, creative, gregarious, persuasive, dramatic, generous, playful. DO: Travel, play, flirt, be optimistic, entertain, be social, write, sing, draw, and paint. Time to network and market your products and services.",
    "4":"Number 4 - BE: Practical, sensible, rational, honest, realistic, loyal, hardworking, serious. DO: Time to plan your work and work your plan, make commitments and agreements, sign contracts, stay late and finish projects, work pays off with rewards of achievement.",
    "5":"Number 5 - BE: Adventurous, different, charismatic, persuasive, extroverted, sensual, impulsive, rebellious. DO: Expect change to show up unannounced, surprises may catch you off guard, be flexible and adaptable, travel, be dynamic, promote your products and services, you are magnetic.",
    "6":"Number 6 - BE: Responsible, care-giver, artistic, friendly, dependable, loving, practical, traditional. DO: Do domestic activities, spend time with family and friends, family and friends may demand more of your time, set boundaries, create more balance in your life, let your heart shine, people want to be with you now.",
    "7":"Number 7 - BE: Reserved, refined, studious, cautious, analytical, deep, selective, mystical. DO: Time to look for answers within, strong Spiritual connections, fate is at work now, meditate, journal, take a trip to reflect on who you are being.",
    "8":"Number 8 - BE: Powerful, ambitious, conservative, confident, efficient, formal, discerning, focused. DO: Excellent month for business and finance, be forceful to create win-win outcomes, apply yourself to the maximum, work with large projects and businesses.",
    "9":"Number 9 - BE: Humanitarian, dreamer, romantic, generous, evolved, impressionable, sensitive, dramatic. DO: Completion and transition are the key words, out with the old and make room for the new, think global, listen, share, reflect, respond, give, surrender, let go let GOD.",
    "11/2":"11/2 Master Number. Number 2 - BE: Sensitive, supportive, unassuming, diplomatic, artistic, friendly, quiet, listener. DO: Take time out to rest and recuperate, learn patience, create relationships, be mindful and thoughtful, reflect, observe and experience, ponder your passion & purpose.",
    "22/4":"22/4 Master Number. Number 4 - BE: Practical, sensible, rational, honest, realistic, loyal, hardworking, serious. DO: Time to plan your work and work your plan, make commitments and agreements, sign contracts, stay late and finish projects, work pays off with rewards of achievement.",
    "33/6":"33/6 Master Number. Number 6 - BE: Responsible, care-giver, artistic, friendly, dependable, loving, practical, traditional. DO: Do domestic activities, spend time with family and friends, family and friends may demand more of your time, set boundaries, create more balance in your life, let your heart shine, people want to be with you now.",
    "13/4":"13/4 Karmic Number. Number 4 - BE: Practical, sensible, rational, honest, realistic, loyal, hardworking, serious. DO: Time to plan your work and work your plan, make commitments and agreements, sign contracts, stay late and finish projects, work pays off with rewards of achievement.",
    "14/5":"14/5 Karmic Number. Number 5 - BE: Adventurous, different, charismatic, persuasive, extroverted, sensual, impulsive, rebellious. DO: Expect change to show up unannounced, surprises may catch you off guard, be flexible and adaptable, travel, be dynamic, promote your products and services, you are magnetic.",
    "16/7":"16/7 Karmic Number. Number 7 - BE: Reserved, refined, studious, cautious, analytical, deep, selective, mystical. DO: Time to look for answers within, strong Spiritual connections, fate is at work now, meditate, journal, take a trip to reflect on who you are being.",
    "19/1":"19/1 Karmic Number. Number 1 - BE: Independent, assertive, original, quick, inventive, mental, strong, principled. DO: Start something new, create original ideas, be confident, take a leadership role, look at new aspects of old plans and ideas, be bold, listen to your intuition."
    },
  "personalDay":{"label":"Personal Day:",
    "0":"",
    "1":"One: Great day for major decisions, new moves and alliances, starting a job, taking a trip with a purpose.  Be honest, assertive, and aim for the top.  A good day for major surgery.",
    "2":"Two: Good day for quiet pursuits, friendships, dates, and meetings.  Wait patiently; study, be especially cooperative; focus on details.  Don't push. Good for a quiet marriage celebration.  Avoid surgery.",
    "3":"Three: A fun day. Good for asking favors. Throw a party. Take a short business trip. Favorable for surgery. Try your luck at the races.  Watch extravagances.",
    "4":"Four: Good for business planning, but not for travel. See your lawyer; undertake money or investment transactions, understand all contracts fully. Go ahead with marriage but watch for complications.  Medical treatments and routine surgery are fine.",
    "5":"Five: A great day for public speaking, networking, partying, and promotion.  Spontaneous start to a trip.  Be aware of possible changes or surprises.  Note the best day for a wedding. Better day for an affair.",
    "6":"Six: Good wedding aspects; great for family reunions or to greet an adopted child.  Divorce proceedings favored.  Avoid heated arguments about petty issues.  Not ideal for travel.  May inherit money.  Health checkups are a good idea.  Do not avoid being alone.",
    "7":"Seven: Good for walks by the sea.  Spend 10 minutes in the morning collecting your thoughts.  Avoid surgery; expect delays.  Do not take an assertive stance.  Do not become frustrated or suicidal because the car won't start.",
    "8":"Eight: A good day to buy or sell property.  All financial matters are favored with clear contracts. Travel on business but for a vacation. Be particularly well-dressed, put on your most authoritative manner.  Present reasons for a raise.",
    "9":"Nine: A wonderful day to spend with friends, working with disadvantaged people, or making hospital visits. Postpone major surgery.  Good for a long-awaited marriage or long-distance flights.  Be especially generous, tolerant, and loving. Avoid dwelling on problems.  Realize tomorrow is another (ONE) day.",
    "11/2":"",
    "22/4":"",
    "33/6":"",
    "13/4":"",
    "14/5":"",
    "16/7":"",
    "19/1":""
    },
	
  "dayOfBirth":{"label":"Day of Birth",
    "1":"Pioneer, Achiever",
    "2":"Sensitive, Peacemaker",
    "3":"Happy, Charming",
    "4":"Builder, Manager",
    "5":"Active, Adaptable",
    "6":"Teacher, Healer",
    "7":"Intellectual, Intuitive",
    "8":"Leader, Manager",
    "9":"Broad-Minded, Idealistic",
    "10":"Leader, Achiever",
    "11/2":"Especially sensitive",
    "12":"Outgoing, Magnetic",
    "13/4":"Builder, Traditionalist",
    "14/5":"Curious, Competitive",
    "15":"Spirited, Open-minded",
    "16/7":"Karmic Friends",
    "17":"Leader, Professional",
    "18":"Idealistic, Executive",
    "19/1":"Leader, Achiever",
    "20":"Conscientious, Spiritual",
    "21":"Optimistic. Dreamer",
    "22/4":"Master Builder",
    "23":"Witty, Independent",
    "24":"Cautious, Productive",
    "25":"Technical, Impressionable",
    "26":"Generous, Introspective",
    "27":"Idealistic, Loving",
    "28":"Independent, Dramatic",
    "29":"Moody, Inspiring",
    "30":"Outspoken, Psychic",
    "31":"Ambitious, Traditional"
    },
	
	
  "firstPinnacle":{"label":"Pinnacles: Events and Environments",
    "0":"",
    "1":"One:  You are developing your confidence, you are involved in new experiences and ideas, and you tend to go your own way in life. You are learning self-reliance.",
    "2":"Two:  You are sensitive and supportive of people; you are learning the art and science of having patience. Interacting with people is very important to you. You are developing your understanding of spaces and timing.",
    "3":"Three:  You learning to be expressive, you are finding your voice; you are developing your artistic abilities. This is an easy time in your life being social and having fun. Creativity is very important.",
    "4":"Four:  You are learning about responsibility and order. This is a serious time in your life. You may feel a need to marry and build or buy a home. You feel like you must get your work completed.",
    "5":"Five:  You are flying by the seat of your pants, you love to travel and explore, and your curious mind draws you into unusual experiences. You may find yourself being drawn into a career where you are selling and or promoting yourself or products.",
    "6":"Six:  You will find yourself wanting to help and teach others. You feel responsible to do the right thing, this is a strong draw to marry and raise a family. You take on a role of service to your friends, family, and community. You develop a sense of justice.",
    "7":"Seven:  You will find yourself wanting to spend more time alone. You have a strong curiosity to study information about the unseen world. You may find yourself so interested in a subject that you may become an expert in that field of interest.",
    "8":"Eight:  You will find yourself gaining confidence in the world of business. You have a strong need to excel and manifest. You are in the energy of management and organization. Now is the ideal time to manage and grow your business to achieve success.",
    "9":"Nine:  You are learning the importance of staying present. You are spending too much time daydreaming and fantasying about the way your life should be lived. You have a strong desire to help the needy; you may find yourself volunteering. You are also drawn to travel globally; you have a strong interest in humanity.",
    "11/2":"11/2:  You have a heightened sense of intuition, you are being asked to listen to your intuition and develop your sense of purpose. You become excited to explore the mysteries of the universe and share your knowledge.",
    "22/4":"22/4:  You have a heightened sense of responsibility and you know there is something you must accomplish in your lifetime.",
    "33/6":"33/6:   You have a strong desire to save the world, to heal the suffering. You may want to start a movement to rid the world of hunger. You may feel like you want to open a healing center. You have a strong sense of purpose.",
    "13/4":"13/4 Karmic Number. You are learning about responsibility and order. This is a serious time in your life. You may feel a need to marry and build or buy a home. You feel like you must get your work completed.",
    "14/5":"14/5 Karmic Number. You are flying by the seat of your pants, you love to travel and explore, and your curious mind draws you into unusual experiences. You may find yourself being drawn into a career where you are selling and or promoting yourself or products.",
    "16/7":"16/7 Karmic Number.You will find yourself wanting to spend more time alone. You have a strong curiosity to study information about the unseen world. You may find yourself so interested in a subject that you may become an expert in that field of interest. ",
    "19/1":"19/1 Karmic Number. You are developing your confidence, you are involved in new experiences and ideas, and you tend to go your own way in life. You are learning self-reliance."
    },
  "secondPinnacle":{"label":"Pinnacles: Events and Environments",
    "0":"",
    "1":"One:  You are developing your confidence, you are involved in new experiences and ideas, and you tend to go your own way in life. You are learning self-reliance.",
    "2":"Two:  You are sensitive and supportive of people; you are learning the art and science of having patience. Interacting with people is very important to you. You are developing your understanding of spaces and timing.",
    "3":"Three:  You learning to be expressive, you are finding your voice; you are developing your artistic abilities. This is an easy time in your life being social and having fun. Creativity is very important.",
    "4":"Four:  You are learning about responsibility and order. This is a serious time in your life. You may feel a need to marry and build or buy a home. You feel like you must get your work completed.",
    "5":"Five:  You are flying by the seat of your pants, you love to travel and explore, and your curious mind draws you into unusual experiences. You may find yourself being drawn into a career where you are selling and or promoting yourself or products.",
    "6":"Six:  You will find yourself wanting to help and teach others. You feel responsible to do the right thing, this is a strong draw to marry and raise a family. You take on a role of service to your friends, family, and community. You develop a sense of justice.",
    "7":"Seven:  You will find yourself wanting to spend more time alone. You have a strong curiosity to study information about the unseen world. You may find yourself so interested in a subject that you may become an expert in that field of interest.",
    "8":"Eight:  You will find yourself gaining confidence in the world of business. You have a strong need to excel and manifest. You are in the energy of management and organization. Now is the ideal time to manage and grow your business to achieve success.",
    "9":"Nine:  You are learning the importance of staying present. You are spending too much time daydreaming and fantasying about the way your life should be lived. You have a strong desire to help the needy; you may find yourself volunteering. You are also drawn to travel globally; you have a strong interest in humanity.",
    "11/2":"11/2:  You have a heightened sense of intuition, you are being asked to listen to your intuition and develop your sense of purpose. You become excited to explore the mysteries of the universe and share your knowledge.",
    "22/4":"22/4:  You have a heightened sense of responsibility and you know there is something you must accomplish in your lifetime.",
    "33/6":"33/6:   You have a strong desire to save the world, to heal the suffering. You may want to start a movement to rid the world of hunger. You may feel like you want to open a healing center. You have a strong sense of purpose.",
    "13/4":" 13/4 Karmic Number. You are learning about responsibility and order. This is a serious time in your life. You may feel a need to marry and build or buy a home. You feel like you must get your work completed.",
    "14/5":"14/5 Karmic Number. You are flying by the seat of your pants, you love to travel and explore, and your curious mind draws you into unusual experiences. You may find yourself being drawn into a career where you are selling and or promoting yourself or products",
    "16/7":"16/7 Karmic Number. You will find yourself wanting to spend more time alone. You have a strong curiosity to study information about the unseen world. You may find yourself so interested in a subject that you may become an expert in that field of interest.",
    "19/1":"19/1 Karmic Number. You are developing your confidence, you are involved in new experiences and ideas, and you tend to go your own way in life. You are learning self-reliance."
    },
  "thirdPinnacle":{"label":"Pinnacles: Events and Environments",
    "0":"",
    "1":"One:  You are developing your confidence, you are involved in new experiences and ideas, and you tend to go your own way in life. You are learning self-reliance.",
    "2":"Two:  You are sensitive and supportive of people; you are learning the art and science of having patience. Interacting with people is very important to you. You are developing your understanding of spaces and timing.",
    "3":"Three:  You learning to be expressive, you are finding your voice; you are developing your artistic abilities. This is an easy time in your life being social and having fun. Creativity is very important.",
    "4":"Four:  You are learning about responsibility and order. This is a serious time in your life. You may feel a need to marry and build or buy a home. You feel like you must get your work completed.",
    "5":"Five:  You are flying by the seat of your pants, you love to travel and explore, and your curious mind draws you into unusual experiences. You may find yourself being drawn into a career where you are selling and or promoting yourself or products.",
    "6":"Six:  You will find yourself wanting to help and teach others. You feel responsible to do the right thing, this is a strong draw to marry and raise a family. You take on a role of service to your friends, family, and community. You develop a sense of justice.",
    "7":"Seven:  You will find yourself wanting to spend more time alone. You have a strong curiosity to study information about the unseen world. You may find yourself so interested in a subject that you may become an expert in that field of interest.",
    "8":"Eight:  You will find yourself gaining confidence in the world of business. You have a strong need to excel and manifest. You are in the energy of management and organization. Now is the ideal time to manage and grow your business to achieve success.",
    "9":"Nine:  You are learning the importance of staying present. You are spending too much time daydreaming and fantasying about the way your life should be lived. You have a strong desire to help the needy; you may find yourself volunteering. You are also drawn to travel globally; you have a strong interest in humanity.",
    "11/2":"Eleven:  You have a heightened sense of intuition, you are being asked to listen to your intuition and develop your sense of purpose. You become excited to explore the mysteries of the universe and share your knowledge.",
    "22/4":"Twenty-Two:  You have a heightened sense of responsibility and you know there is something you must accomplish in your lifetime.",
    "33/6":"Thirty-Three:   You have a strong desire to save the world, to heal the suffering. You may want to start a movement to rid the world of hunger. You may feel like you want to open a healing center. You have a strong sense of purpose.",
    "13/4":" 13/4 Karmic Number. You are learning about responsibility and order. This is a serious time in your life. You may feel a need to marry and build or buy a home. You feel like you must get your work completed.",
    "14/5":"14/5 Karmic Number. You are flying by the seat of your pants, you love to travel and explore, and your curious mind draws you into unusual experiences. You may find yourself being drawn into a career where you are selling and or promoting yourself or products",
    "16/7":"16/7 Karmic Number. You will find yourself wanting to spend more time alone. You have a strong curiosity to study information about the unseen world. You may find yourself so interested in a subject that you may become an expert in that field of interest.",
    "19/1":"19/1 Karmic Number. You are developing your confidence, you are involved in new experiences and ideas, and you tend to go your own way in life. You are learning self-reliance."
    },
  "fourthPinnacle":{"label":"Pinnacles: Events and Environments",
    "0":"",
    "1":"One:  You are developing your confidence, you are involved in new experiences and ideas, and you tend to go your own way in life. You are learning self-reliance.",
    "2":"Two:  You are sensitive and supportive of people; you are learning the art and science of having patience. Interacting with people is very important to you. You are developing your understanding of spaces and timing.",
    "3":"Three:  You learning to be expressive, you are finding your voice; you are developing your artistic abilities. This is an easy time in your life being social and having fun. Creativity is very important.",
    "4":"Four:  You are learning about responsibility and order. This is a serious time in your life. You may feel a need to marry and build or buy a home. You feel like you must get your work completed.",
    "5":"Five:  You are flying by the seat of your pants, you love to travel and explore, and your curious mind draws you into unusual experiences. You may find yourself being drawn into a career where you are selling and or promoting yourself or products.",
    "6":"Six:  You will find yourself wanting to help and teach others. You feel responsible to do the right thing, this is a strong draw to marry and raise a family. You take on a role of service to your friends, family, and community. You develop a sense of justice.",
    "7":"Seven:  You will find yourself wanting to spend more time alone. You have a strong curiosity to study information about the unseen world. You may find yourself so interested in a subject that you may become an expert in that field of interest.",
    "8":"Eight:  You will find yourself gaining confidence in the world of business. You have a strong need to excel and manifest. You are in the energy of management and organization. Now is the ideal time to manage and grow your business to achieve success.",
    "9":"Nine:  You are learning the importance of staying present. You are spending too much time daydreaming and fantasying about the way your life should be lived. You have a strong desire to help the needy; you may find yourself volunteering. You are also drawn to travel globally; you have a strong interest in humanity.",
    "11/2":"Eleven:  You have a heightened sense of intuition, you are being asked to listen to your intuition and develop your sense of purpose. You become excited to explore the mysteries of the universe and share your knowledge.",
    "22/4":"Twenty-Two:  You have a heightened sense of responsibility and you know there is something you must accomplish in your lifetime.",
    "33/6":"Thirty-Three:   You have a strong desire to save the world, to heal the suffering. You may want to start a movement to rid the world of hunger. You may feel like you want to open a healing center. You have a strong sense of purpose.",
    "13/4":" 13/4 Karmic Number. You are learning about responsibility and order. This is a serious time in your life. You may feel a need to marry and build or buy a home. You feel like you must get your work completed.",
    "14/5":"14/5 Karmic Number. You are flying by the seat of your pants, you love to travel and explore, and your curious mind draws you into unusual experiences. You may find yourself being drawn into a career where you are selling and or promoting yourself or products",
    "16/7":"16/7 Karmic Number. You will find yourself wanting to spend more time alone. You have a strong curiosity to study information about the unseen world. You may find yourself so interested in a subject that you may become an expert in that field of interest.",
    "19/1":"19/1 Karmic Number. You are developing your confidence, you are involved in new experiences and ideas, and you tend to go your own way in life. You are learning self-reliance."
    },

  "firstChallenge":{"label":"Challenges: Inner Limitations",
    "0":"Zero:  Metaphysics teach that you create your own challenges. If you have a zero challenge at this time, it tells you that you have no outside challenges at this time in your life. If you find challenges, you need to own up to the source. . . YOU!",
    "1":"One:  You are learning survival skills. You may have a strong dominate parent that challenges you. You are learning to trust yourself. You may be dealing with handling some issues around your anger and quick temper.",
    "2":"Two:  Relationships are your teachers; you may be challenged to understand how to be in a happy, healthy relationship. You may find yourself frustrated with having to wait for others. You may not understand how to be a good partner.",
    "3":"Three:  You may not feel it is important to express yourself. You are challenged to communicate your feelings. You have a difficult time believing you have any creative abilities.",
    "4":"Four:  You feel trapped and restricted with routines and systems you are involved with. You have a difficult time following the rules; you don’t seem to be able to get out of the ruts you may have created.",
    "5":"Five:  You are restless and have a difficult time staying focused and completing tasks and projects. Your avant-guard attitude gets you into trouble. You feel trapped and crave freedom.",
    "6":"Six:  You may find that your commitments have caused you to become over loaded with responsibility. Your friends and family responsibilities may seem to consume too much of your personal time.",
    "7":"Seven:  You may find you have trust issues with people. You will be drawn to spend time alone with your thoughts. You may find yourself becoming isolated and or lonely. Superficial conversations bore you.",
    "8":"Eight:  You may find yourself spending lots of time at work. You are driven to accomplish and produce. You have a passion to create wealth at all costs. You may find yourself dominating your fellow workers if they can’t keep up the pace.",
    "9":""
    },
  "secondChallenge":{"label":"Challenges: Inner Limitations",
    "0":"Zero:  Metaphysics teach that you create your own challenges. If you have a zero challenge at this time, it tells you that you have no outside challenges at this time in your life. If you find challenges, you need to own up to the source. . . YOU!",
    "1":"One:  You are learning survival skills. You may have a strong dominate parent that challenges you. You are learning to trust yourself. You may be dealing with handling some issues around your anger and quick temper.",
    "2":"Two:  Relationships are your teachers; you may be challenged to understand how to be in a happy, healthy relationship. You may find yourself frustrated with having to wait for others. You may not understand how to be a good partner.",
    "3":"Three:  You may not feel it is important to express yourself. You are challenged to communicate your feelings. You have a difficult time believing you have any creative abilities.",
    "4":"Four:  You feel trapped and restricted with routines and systems you are involved with. You have a difficult time following the rules; you don’t seem to be able to get out of the ruts you may have created.",
    "5":"Five:  You are restless and have a difficult time staying focused and completing tasks and projects. Your avant-guard attitude gets you into trouble. You feel trapped and crave freedom.",
    "6":"Six:  You may find that your commitments have caused you to become over loaded with responsibility. Your friends and family responsibilities may seem to consume too much of your personal time.",
    "7":"Seven:  You may find you have trust issues with people. You will be drawn to spend time alone with your thoughts. You may find yourself becoming isolated and or lonely. Superficial conversations bore you.",
    "8":"Eight:  You may find yourself spending lots of time at work. You are driven to accomplish and produce. You have a passion to create wealth at all costs. You may find yourself dominating your fellow workers if they can’t keep up the pace.",
    "9":""
    },
  "thirdChallenge":{"label":"Challenges: Inner Limitations",
    "0":"Zero:  Metaphysics teach that you create your own challenges. If you have a zero challenge at this time, it tells you that you have no outside challenges at this time in your life. If you find challenges, you need to own up to the source. . . YOU!",
    "1":"One:  You are learning survival skills. You may have a strong dominate parent that challenges you. You are learning to trust yourself. You may be dealing with handling some issues around your anger and quick temper.",
    "2":"Two:  Relationships are your teachers; you may be challenged to understand how to be in a happy, healthy relationship. You may find yourself frustrated with having to wait for others. You may not understand how to be a good partner.",
    "3":"Three:  You may not feel it is important to express yourself. You are challenged to communicate your feelings. You have a difficult time believing you have any creative abilities.",
    "4":"Four:  You feel trapped and restricted with routines and systems you are involved with. You have a difficult time following the rules; you don’t seem to be able to get out of the ruts you may have created.",
    "5":"Five:  You are restless and have a difficult time staying focused and completing tasks and projects. Your avant-guard attitude gets you into trouble. You feel trapped and crave freedom.",
    "6":"Six:  You may find that your commitments have caused you to become over loaded with responsibility. Your friends and family responsibilities may seem to consume too much of your personal time.",
    "7":"Seven:  You may find you have trust issues with people. You will be drawn to spend time alone with your thoughts. You may find yourself becoming isolated and or lonely. Superficial conversations bore you.",
    "8":"Eight:  You may find yourself spending lots of time at work. You are driven to accomplish and produce. You have a passion to create wealth at all costs. You may find yourself dominating your fellow workers if they can’t keep up the pace.",
    "9":""
    },
  "fourthChallenge":{"label":"Challenges: Inner Limitations",
    "0":"Zero:  Metaphysics teach that you create your own challenges. If you have a zero challenge at this time, it tells you that you have no outside challenges at this time in your life. If you find challenges, you need to own up to the source. . . YOU!",
    "1":"One:  You are learning survival skills. You may have a strong dominate parent that challenges you. You are learning to trust yourself. You may be dealing with handling some issues around your anger and quick temper.",
    "2":"Two:  Relationships are your teachers; you may be challenged to understand how to be in a happy, healthy relationship. You may find yourself frustrated with having to wait for others. You may not understand how to be a good partner.",
    "3":"Three:  You may not feel it is important to express yourself. You are challenged to communicate your feelings. You have a difficult time believing you have any creative abilities.",
    "4":"Four:  You feel trapped and restricted with routines and systems you are involved with. You have a difficult time following the rules; you don’t seem to be able to get out of the ruts you may have created.",
    "5":"Five:  You are restless and have a difficult time staying focused and completing tasks and projects. Your avant-guard attitude gets you into trouble. You feel trapped and crave freedom.",
    "6":"Six:  You may find that your commitments have caused you to become over loaded with responsibility. Your friends and family responsibilities may seem to consume too much of your personal time.",
    "7":"Seven:  You may find you have trust issues with people. You will be drawn to spend time alone with your thoughts. You may find yourself becoming isolated and or lonely. Superficial conversations bore you.",
    "8":"Eight:  You may find yourself spending lots of time at work. You are driven to accomplish and produce. You have a passion to create wealth at all costs. You may find yourself dominating your fellow workers if they can’t keep up the pace.",
    "9":""
    },


  "count1":{"label":"1",
    "0":"You are not confident.",
    "1":"You are not confident.",
    "2":"You have an average amount of confidence.",
    "3":"You have an average amount of confidence.",
    "4":"You are confident; you have a desire to lead.",
    "5":"You are so confident that you don’t listen to others.",
    "6":"You are so confident that you don’t listen to others.",
    "7":"You are so confident that you don’t listen to others.",
    "8":"You are so confident that you don’t listen to others.",
    "9":"You are so confident that you don’t listen to others."
    },
  "count2":{"label":"2",
    "0":"You are impatient and have little follow-through to complete things.",
    "1":"You are patient and will cooperate.",
    "2":"You are patient and will cooperate.",
    "3":"You are patient and will cooperate.",
    "4":"You are patient and will cooperate.",
    "5":"You are patient and will cooperate.",
    "6":"You are patient and will cooperate.",
    "7":"You are patient and will cooperate.",
    "8":"You are patient and will cooperate.",
    "9":"You are patient and will cooperate."
    },
  "count3":{"label":"3",
    "0":"You can be challenged with articulating what you mean.",
    "1":"You can be creative.",
    "2":"You can be creative.",
    "3":"You can be creative.",
    "4":"You have good communication skills; you are optimistic; you are creative.",
    "5":"You have good communication skills; you are optimistic; you are creative.",
    "6":"You have good communication skills; you are optimistic; you are creative.",
    "7":"You have good communication skills; you are optimistic; you are creative.",
    "8":"You have good communication skills; you are optimistic; you are creative.",
    "9":"You have good communication skills; you are optimistic; you are creative."
    },
  "count4":{"label":"4",
    "0":"You are not practical. If 4 is the only missing number, it is a sign of good health.",
    "1":"You are good at implementing other people’s ideas.",
    "2":"You are good at implementing other people’s ideas.",
    "3":"You are extremely practical; you are a hard worker.",
    "4":"You are extremely practical; you are a hard worker.",
    "5":"You are extremely practical; you are a hard worker.",
    "6":"You are extremely practical; you are a hard worker.",
    "7":"You are extremely practical; you are a hard worker.",
    "8":"You are extremely practical; you are a hard worker.",
    "9":"You are extremely practical; you are a hard worker."
    },
  "count5":{"label":"5",
    "0":"You are not competitive or curious.",
    "1":"You are not competitive or curious.",
    "2":"You are not competitive or curious.",
    "3":"You are flexible and adaptable.",
    "4":"You are flexible and adaptable.",
    "5":"You need lots of personal freedom. You have excellent sales ability.",
    "6":"You need lots of personal freedom. You have excellent sales ability.",
    "7":"You need lots of personal freedom. You have excellent sales ability.",
    "8":"You need lots of personal freedom. You have excellent sales ability.",
    "9":"You need lots of personal freedom. You have excellent sales ability."
    },
  "count6":{"label":"6",
    "0":"You will probably marry more than once.",
    "1":"You have good judgment; you rescue people.",
    "2":"You have good judgment; you rescue people.",
    "3":"You are traditional, opinionated, and loyal.",
    "4":"You are traditional, opinionated, and loyal.",
    "5":"You are traditional, opinionated, and loyal.",
    "6":"You are traditional, opinionated, and loyal.",
    "7":"You are traditional, opinionated, and loyal.",
    "8":"You are traditional, opinionated, and loyal.",
    "9":"You are traditional, opinionated, and loyal."
    },
  "count7":{"label":"7",
    "0":"You are open-minded; a tireless worker, you are curious.",
    "1":"You have exceptional memory and a spiritual interest.",
    "2":"You have exceptional memory and a spiritual interest",
    "3":"You are eccentric, analytical and aloof.",
    "4":"You are eccentric, analytical and aloof.",
    "5":"You are eccentric, analytical and aloof.",
    "6":"You are eccentric, analytical and aloof.",
    "7":"You are eccentric, analytical and aloof.",
    "8":"You are eccentric, analytical and aloof.",
    "9":"You are eccentric, analytical and aloof."
    },
  "count8":{"label":"8",
    "0":"People will offer to help you. Money is unimportant to you; it is for the higher purpose. If you are unattached to money it will magically come to you. You do something for the love of doing it not for the money it brings you.",
    "1":"You like to supervise people; you are reliable.",
    "2":"You are extremely hard working; you like to work with money.",
    "3":"You are extremely hard working; you like to work with money.",
    "4":"You are extremely hard working; you like to work with money.",
    "5":"You are extremely hard working; you like to work with money.",
    "6":"You are extremely hard working; you like to work with money.",
    "7":"You are extremely hard working; you like to work with money.",
    "8":"You are extremely hard working; you like to work with money.",
    "9":"You are extremely hard working; you like to work with money."
    },
  "count9":{"label":"9",
    "0":"You have trouble finishing projects.",
    "1":"You are compassionate; have idealistic goals; you enjoy romance.",
    "2":"You are compassionate; have idealistic goals; you enjoy romance.",
    "3":"You are compassionate; have idealistic goals; you enjoy romance.",
    "4":"You are compassionate; have idealistic goals; you enjoy romance.",
    "5":"You are compassionate; have idealistic goals; you enjoy romance.",
    "6":"You are extremely emotional and vulnerable to outside influences. You may be moody. You will do well to be careful about becoming narcissistic.",
    "7":"You are extremely emotional and vulnerable to outside influences. You may be moody. You will do well to be careful about becoming narcissistic.",
    "8":"You are extremely emotional and vulnerable to outside influences. You may be moody. You will do well to be careful about becoming narcissistic.",
    "9":"You are extremely emotional and vulnerable to outside influences. You may be moody. You will do well to be careful about becoming narcissistic."
    },
  "karmicLesson":{"label":"Karmic Lesson",
    "1":"One: Learn to be Independent, develop confidence, become a leader",
    "2":"Two: Learning about relationships will teach you your life lessons",
    "3":"Three: Learn to express your feelings, find your voice, express yourself",
    "4":"Four: Learn to apply yourself, understand structure, focus ",
    "5":"Five: Learn to be flexible and adaptable, take calculated risks",
    "6":"Six: Learn how to set boundaries, learn to receive, learn balance",
    "7":"Seven: Learn to trust, seek to understand the unseen world, develop intuition",
    "8":"Eight: Learn about the energy of money, learn about management energy",
    "9":"Nine: Learn about catch and release, learn about values, learn about reality"    },
  "findInput":{"label":""
    }
    
  };
        
        
/*
  "personalDay":{"label":"Personal Day:",
    "0":"",
    "1":"",
    "2":"",
    "3":"",
    "4":"",
    "5":"",
    "6":"",
    "7":"",
    "8":"",
    "9":"",
    "11/2":"",
    "22/4":"",
    "33/6":"",
    "13/4":"",
    "14/5":"",
    "16/7":"",
    "19/1":""
    },
//unused meta fields
  "firstNameInput":{"label":"First Name"},
  "middleNameInput":{"label":"Middle Name"},
  "lastNameInput":{"label":"Last Name"},
  "birthdayInput":{"label":"Birthday"},
  "dayOfWeek":{"label":""},
  "dayOfYear":{"label":""},
  "firstName":{"label":"First Name"},
  "middleName":{"label":"Middle Name"},
  "lastName":{"label":"Last Name"},

*/